# **ICMP FLOW-LEVEL FEATURE GENERATOR**

Packet-to-Flow Converter for Covert Channel Detection

Handles unidirectional ICMP traffic with proper flow identification

# **Importing Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# **Reading Packet Level Features CSV files**

In [ ]:
packetlevel1 =pd.read_csv("/content/ICMP-PACKET1ST-FINAL.csv", encoding='latin1')

In [ ]:
packetlevel2  =pd.read_csv("/content/ICMP-PACKETLEVEL2ND-FINAL.csv", encoding='latin1')

In [ ]:
packetlevel1.head()

,No.,Time,Source,Destination,Protocol,Length,Type,Checksum,Identifier (BE),Identifier (LE),...,Type.1,Code,Checksum Status,Sequence Number (BE),Sequence Number (LE),Data.1,Length.1,Frame Length,Capture Length,Info
0,1,0.000000,192.168.8.132,192.168.8.130,ICMP,82,IPv4,0xdedf,4.0,1024.0,...,Echo (ping) request,0,Good,3.0,768.0,â\234\223,40.0,82,82,"Echo (ping) request id=0x0004, seq=3/768, ttl..."
1,2,0.000652,192.168.8.132,192.168.8.130,ICMP,98,IPv4,0x8503,62751.0,8181.0,...,Echo (ping) request,0,Good,1637.0,25862.0,â\234\223,56.0,98,98,"Echo (ping) request id=0xf51f, seq=1637/25862..."
2,3,0.001147,192.168.8.132,192.168.8.130,"ICMP, HiPerConTracer",1442,IPv4,0xac74,810.0,10755.0,...,Echo (ping) request,0,Good,809.0,10499.0,NaN,NaN,1442,1442,"Echo (ping) request id=0x032a, seq=809/10499,..."
3,4,0.002966,192.168.8.132,192.168.8.130,ICMP,82,IPv4,0xbebf,4116.0,5136.0,...,Echo (ping) request,0,Good,4115.0,4880.0,â\234\223,40.0,82,82,"Echo (ping) request id=0x1014, seq=4115/4880,..."
4,5,0.009979,192.168.8.132,192.168.8.130,ICMP,60,IPv4,0x1713,3320.0,63500.0,...,Echo (ping) request,0,Good,3319.0,63244.0,â\234\223,8.0,60,60,"Echo (ping) request id=0x0cf8, seq=3319/63244..."

In [ ]:
packetlevel1.tail()

,No.,Time,Source,Destination,Protocol,Length,Type,Checksum,Identifier (BE),Identifier (LE),...,Type.1,Code,Checksum Status,Sequence Number (BE),Sequence Number (LE),Data.1,Length.1,Frame Length,Capture Length,Info
100051,100052,2938.337775,192.168.8.132,192.168.8.131,ICMP,65,IPv4,0xf075,34444.0,35974.0,...,Echo (ping) request,0,Good,34443.0,35718.0,â\234\223,23.0,65,65,"Echo (ping) request id=0x868c, seq=34443/3571..."
100052,100053,2938.428358,192.168.8.132,192.168.8.131,ICMP,98,IPv4,0x736e,34445.0,36230.0,...,Echo (ping) request,0,Good,34444.0,35974.0,â\234\223,56.0,98,98,"Echo (ping) request id=0x868d, seq=34444/3597..."
100053,100054,2938.492266,192.168.8.132,192.168.8.131,ICMP,82,IPv4,0xa9a2,34446.0,36486.0,...,Echo (ping) request,0,Good,34445.0,36230.0,â\234\223,40.0,82,82,"Echo (ping) request id=0x868e, seq=34445/3623..."
100054,100055,2938.564054,192.168.8.132,192.168.8.131,ICMP,82,IPv4,0xa990,34455.0,38790.0,...,Echo (ping) request,0,Good,34454.0,38534.0,â\234\223,40.0,82,82,"Echo (ping) request id=0x8697, seq=34454/3853..."
100055,100056,2938.632433,192.168.8.132,192.168.8.131,ICMP,107,IPv4,0xe31f,34460.0,40070.0,...,Echo (ping) request,0,Good,34459.0,39814.0,â\234\223,65.0,107,107,"Echo (ping) request id=0x869c, seq=34459/3981..."

In [ ]:
packetlevel1.shape

(100056, 29)

In [ ]:
packetlevel1.columns.to_list()

['No.',
 'Time',
 'Source',
 'Destination',
 'Protocol',
 'Length',
 'Type',
 'Checksum',
 'Identifier (BE)',
 'Identifier (LE)',
 'Total Length',
 'Header Length',
 'Flags',
 'Header Checksum',
 'Data',
 'Identification',
 'Explicit Congestion Notification',
 'Differentiated Services Codepoint',
 'Fragment Offset',
 'Type.1',
 'Code',
 'Checksum Status',
 'Sequence Number (BE)',
 'Sequence Number (LE)',
 'Data.1',
 'Length.1',
 'Frame Length',
 'Capture Length',
 'Info']

In [ ]:
packetlevel2.head()

,No.,Time,Source,Destination,Protocol,Length,Type,Checksum,Identifier (BE),Identifier (LE),...,Type.1,Code,Checksum Status,Sequence Number (BE),Sequence Number (LE),Data.1,Length.1,Frame Length,Capture Length,Info
0,1,0.000000,192.168.8.132,192.168.8.131,ICMP,62,IPv4,0x0cbc,NaN,NaN,...,Time-to-live exceeded,0,Good,NaN,NaN,NaN,NaN,62,62,Time-to-live exceeded (Time to live exceeded i...
1,2,0.000563,192.168.8.132,192.168.8.131,ICMP,82,IPv4,0xb8fb,8905.0,51490.0,...,Echo (ping) request,0,Good,802.0,8707.0,â\234\223,40.0,82,82,"Echo (ping) request id=0x22c9, seq=802/8707, ..."
2,3,0.001751,192.168.8.132,192.168.8.131,"ICMP, HiPerConTracer",82,IPv4,0x121d,804.0,9219.0,...,Echo (ping) request,0,Bad,803.0,8963.0,NaN,NaN,82,82,"Echo (ping) request id=0x0324, seq=803/8963, ..."
3,4,0.002121,192.168.8.132,192.168.8.131,ICMP,74,IPv4,0xb2d7,33436.0,40066.0,...,Echo (ping) request,0,Good,2499.0,49929.0,â\234\223,32.0,74,74,"Echo (ping) request id=0x829c, seq=2499/49929..."
4,5,0.002892,192.168.8.132,192.168.8.131,"ICMP, HiPerConTracer",82,IPv4,0xe3c5,5776.0,36886.0,...,Echo (ping) request,0,Bad,5775.0,36630.0,NaN,NaN,82,82,"Echo (ping) request id=0x1690, seq=5775/36630..."

In [ ]:
packetlevel1.columns.to_list()

['No.',
 'Time',
 'Source',
 'Destination',
 'Protocol',
 'Length',
 'Type',
 'Checksum',
 'Identifier (BE)',
 'Identifier (LE)',
 'Total Length',
 'Header Length',
 'Flags',
 'Header Checksum',
 'Data',
 'Identification',
 'Explicit Congestion Notification',
 'Differentiated Services Codepoint',
 'Fragment Offset',
 'Type.1',
 'Code',
 'Checksum Status',
 'Sequence Number (BE)',
 'Sequence Number (LE)',
 'Data.1',
 'Length.1',
 'Frame Length',
 'Capture Length',
 'Info']

In [ ]:
packetlevel1.tail()

,No.,Time,Source,Destination,Protocol,Length,Type,Checksum,Identifier (BE),Identifier (LE),...,Type.1,Code,Checksum Status,Sequence Number (BE),Sequence Number (LE),Data.1,Length.1,Frame Length,Capture Length,Info
100051,100052,2938.337775,192.168.8.132,192.168.8.131,ICMP,65,IPv4,0xf075,34444.0,35974.0,...,Echo (ping) request,0,Good,34443.0,35718.0,â\234\223,23.0,65,65,"Echo (ping) request id=0x868c, seq=34443/3571..."
100052,100053,2938.428358,192.168.8.132,192.168.8.131,ICMP,98,IPv4,0x736e,34445.0,36230.0,...,Echo (ping) request,0,Good,34444.0,35974.0,â\234\223,56.0,98,98,"Echo (ping) request id=0x868d, seq=34444/3597..."
100053,100054,2938.492266,192.168.8.132,192.168.8.131,ICMP,82,IPv4,0xa9a2,34446.0,36486.0,...,Echo (ping) request,0,Good,34445.0,36230.0,â\234\223,40.0,82,82,"Echo (ping) request id=0x868e, seq=34445/3623..."
100054,100055,2938.564054,192.168.8.132,192.168.8.131,ICMP,82,IPv4,0xa990,34455.0,38790.0,...,Echo (ping) request,0,Good,34454.0,38534.0,â\234\223,40.0,82,82,"Echo (ping) request id=0x8697, seq=34454/3853..."
100055,100056,2938.632433,192.168.8.132,192.168.8.131,ICMP,107,IPv4,0xe31f,34460.0,40070.0,...,Echo (ping) request,0,Good,34459.0,39814.0,â\234\223,65.0,107,107,"Echo (ping) request id=0x869c, seq=34459/3981..."

In [ ]:
packetlevel1.shape

(100056, 29)

# **ICMP Packet to flow level Extractor**

In [ ]:
"""
ICMP Flow-Level Feature Extractor
===================================
Combines two 29-column Wireshark packet-level CSV files and extracts
flow-level features specifically for 3 covert channel techniques:

  Class 0 — Header Manipulation
  Class 1 — Flow Blending
  Class 2 — Time Obfuscation

Flow splitting: TTL group × 5-second sliding window (2.5s step)
Output: icmp_flow_features_final.csv

Usage:
  python flow_extractor_final.py
"""

import re, warnings, itertools, zlib
import numpy as np
import pandas as pd
from scipy import stats
from scipy.fft import rfft

warnings.filterwarnings("ignore")

# ══════════════════════════════════════════════════════════════════════
# CONFIG — update file paths if needed
# ══════════════════════════════════════════════════════════════════════
FILE1       = "/content/ICMP-PACKET1ST-FINAL.csv"   # 17,790 rows  (enriched, has bad checksums)
FILE2       = "/content/ICMP-PACKETLEVEL2ND-FINAL.csv"  # 100,056 rows

OUTPUT_CSV  = "icmp_flow_features_final.csv"

WINDOW_SEC  = 5.0    # flow window size in seconds
STEP_SEC    = 2.5    # sliding step (50% overlap)
MIN_PKTS    = 5      # minimum packets to keep a window
IDLE_THR    = 1.0    # seconds — idle period threshold
BURST_GAP   = 0.2   # seconds — burst separation gap
FLOWS_PER_CLASS = 500   # cap per class for balance
RANDOM_SEED = 42

# TTL → class label mapping
# 64  = Header Manipulation (standard Linux ICMP, bad checksums in File1)
# 128 = Flow Blending       (Windows-style, large payloads)
# 255 = Time Obfuscation    (network device, precise timing)
TTL_LABEL = {64: 0, 128: 1, 255: 2}
LABEL_NAME = {0: "Header_Manipulation", 1: "Flow_Blending", 2: "Time_Obfuscation"}

np.random.seed(RANDOM_SEED)

# ══════════════════════════════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════════════════════════════

RE_TTL  = re.compile(r'ttl=(\d+)',          re.I)
RE_ID   = re.compile(r'id=0x([0-9a-fA-F]+)')
RE_SEQ  = re.compile(r'seq=(\d+)/')
RE_TYPE = re.compile(r'Echo \(ping\) (request|reply)', re.I)
COVERT_IDS = {0xDEAD, 0xBEEF, 0xCAFE, 0xFACE, 0xFEED, 0x1337, 0x4141}

def parse_info(s):
    s = str(s)
    m = RE_TYPE.search(s); mt = m.group(1).lower() if m else 'other'
    m = RE_ID.search(s);   ci = int(m.group(1), 16) if m else np.nan
    m = RE_SEQ.search(s);  sq = int(m.group(1))     if m else np.nan
    m = RE_TTL.search(s);  tt = int(m.group(1))     if m else np.nan
    return mt, ci, sq, tt

def safe_entropy(vals):
    arr = np.asarray(vals, dtype=float)
    if len(arr) < 2 or arr.std() == 0: return 0.0
    bins = np.linspace(arr.min(), arr.max() + 1e-9, 257)
    c, _ = np.histogram(arr, bins=bins)
    p = c / c.sum(); p = p[p > 0]
    return float(-np.sum(p * np.log2(p)))

def kl_divergence(sizes, mu=84, sd=30):
    arr = np.asarray(sizes, dtype=float)
    if len(arr) < 2: return 0.0
    bins = np.linspace(arr.min()-1, arr.max()+1, 33)
    p, _ = np.histogram(arr, bins=bins, density=True)
    q = stats.norm.pdf((bins[:-1]+bins[1:])/2, mu, sd)
    p += 1e-10; q += 1e-10; p /= p.sum(); q /= q.sum()
    return float(np.sum(p * np.log(p / q)))

def periodicity_score(ipt):
    if len(ipt) < 8: return 0.0
    arr  = np.asarray(ipt, dtype=float) - np.mean(ipt)
    spec = np.abs(rfft(arr)) ** 2
    return float(spec[1:].max() / spec[1:].sum()) if spec[1:].sum() > 0 else 0.0

def burst_analysis(times):
    t = np.sort(times)
    if len(t) < 2: return 1, [len(t)], []
    d = np.diff(t); bl, ib, c = [], [], 1
    for v in d:
        if v > BURST_GAP: bl.append(c); ib.append(float(v)); c = 1
        else: c += 1
    bl.append(c)
    return len(bl), bl, ib

def idle_periods(times):
    if len(times) < 2: return 0, []
    d = np.diff(np.sort(times)); il = d[d > IDLE_THR]
    return int(len(il)), list(il)

def payload_byte_features(hex_series):
    """Aggregate byte-level features across all payload hex strings in a flow."""
    entropies, comp_ratios, print_ratios, null_ratios, bigram_entropies = [], [], [], [], []
    for h in hex_series.dropna():
        h = str(h).replace(':', '').replace(' ', '').strip()
        if not h or not all(c in '0123456789abcdefABCDEF' for c in h):
            continue
        try:
            raw = bytes.fromhex(h)
        except Exception:
            continue
        if len(raw) == 0:
            continue
        arr = np.frombuffer(raw, dtype=np.uint8)
        # Byte entropy
        cnt = np.bincount(arr, minlength=256)
        p   = cnt / cnt.sum(); p_nz = p[p > 0]
        entropies.append(float(-np.sum(p_nz * np.log2(p_nz))))
        # Compression ratio
        try:    comp_ratios.append(len(zlib.compress(raw, 9)) / len(raw))
        except: pass
        # Printable ratio
        print_ratios.append(sum(32 <= b <= 126 for b in arr) / len(arr))
        # Null byte ratio
        null_ratios.append(float(np.sum(arr == 0) / len(arr)))
        # Bigram entropy
        if len(arr) >= 2:
            bg = arr[:-1].astype(int) * 256 + arr[1:].astype(int)
            bc = np.bincount(bg, minlength=65536) / len(bg)
            bc_nz = bc[bc > 0]
            bigram_entropies.append(float(-np.sum(bc_nz * np.log2(bc_nz))))

    def agg(lst):
        return (float(np.mean(lst)), float(np.std(lst))) if lst else (np.nan, np.nan)

    e_m,  e_s  = agg(entropies)
    cr_m, cr_s = agg(comp_ratios)
    pr_m, pr_s = agg(print_ratios)
    nr_m, nr_s = agg(null_ratios)
    bg_m, bg_s = agg(bigram_entropies)

    return {
        'pld_byte_entropy_mean':    e_m,  'pld_byte_entropy_std':    e_s,
        'pld_compress_ratio_mean':  cr_m, 'pld_compress_ratio_std':  cr_s,
        'pld_printable_ratio_mean': pr_m, 'pld_printable_ratio_std': pr_s,
        'pld_null_ratio_mean':      nr_m, 'pld_null_ratio_std':      nr_s,
        'pld_bigram_entropy_mean':  bg_m, 'pld_bigram_entropy_std':  bg_s,
    }

# ══════════════════════════════════════════════════════════════════════
# FEATURE EXTRACTION — per window
# ══════════════════════════════════════════════════════════════════════

def extract_flow_features(grp, has_raw_payload=False, has_checksum_col=False):
    """
    Extract all flow-level features from a packet window (DataFrame).
    Returns a flat dict of features, or None if window too small.
    """
    grp = grp.sort_values('time').reset_index(drop=True)
    n   = len(grp)
    if n < MIN_PKTS:
        return None

    req   = grp[grp['msg_type'] == 'request']
    rep   = grp[grp['msg_type'] == 'reply']
    times = grp['time'].values.astype(float)
    lens  = grp['length'].values.astype(float)
    pld   = (lens - 42).clip(0)   # payload = total - Eth(14)+IP(20)+ICMP(8)
    ttls  = grp['ttl'].dropna().values.astype(float)
    seqs  = grp['icmp_seq'].dropna().values.astype(float)
    ids   = grp['icmp_id'].dropna().values.astype(float)
    ipt   = np.diff(times) if n > 1 else np.array([0.0])

    f = {}

    # ── HEADER MANIPULATION FEATURES ─────────────────────────────────

    # ICMP type/code distribution
    tc   = grp['msg_type'].value_counts()
    tp   = (tc / tc.sum()).values
    f['hm_type_code_entropy']    = float(-np.sum(tp * np.log2(tp + 1e-10)))
    f['hm_invalid_type_ratio']   = float(tc.get('other', 0) / n)
    f['hm_non_echo_ratio']       = float((grp['msg_type'] != 'request').sum() / n)

    # Raw ICMP type diversity (from Type.1 column)
    if 'icmp_type_raw' in grp.columns:
        type_counts = grp['icmp_type_raw'].value_counts()
        type_probs  = (type_counts / type_counts.sum()).values
        f['hm_icmp_type_diversity'] = float(
            -np.sum(type_probs * np.log2(type_probs + 1e-10)))
        f['hm_nonstandard_type_count'] = int(
            (~grp['icmp_type_raw'].str.contains('Echo', na=False)).sum())
    else:
        f['hm_icmp_type_diversity']    = 0.0
        f['hm_nonstandard_type_count'] = 0

    # ICMP code features
    if 'icmp_code' in grp.columns:
        codes = pd.to_numeric(grp['icmp_code'], errors='coerce').dropna()
        f['hm_code_entropy']       = safe_entropy(codes)
        f['hm_nonzero_code_ratio'] = float((codes != 0).sum() / max(len(codes), 1))
    else:
        f['hm_code_entropy']       = 0.0
        f['hm_nonzero_code_ratio'] = 0.0

    # Checksum validity
    if has_checksum_col and 'chk_status' in grp.columns:
        f['hm_bad_checksum_ratio']  = float((grp['chk_status'] == 'Bad').sum() / n)
        f['hm_good_checksum_ratio'] = float((grp['chk_status'] == 'Good').sum() / n)
    else:
        f['hm_bad_checksum_ratio']  = 0.0
        f['hm_good_checksum_ratio'] = 1.0

    # ICMP checksum hex entropy
    if 'checksum_hex' in grp.columns:
        chk_vals = grp['checksum_hex'].dropna().apply(
            lambda x: int(str(x).replace('0x',''), 16) if str(x).startswith('0x') else 0)
        f['hm_checksum_entropy'] = safe_entropy(chk_vals)
        if len(chk_vals) > 1:
            d = np.diff(chk_vals.values.astype(float))
            f['hm_checksum_delta_mean'] = float(np.mean(np.abs(d)))
            f['hm_checksum_delta_std']  = float(np.std(d))
        else:
            f['hm_checksum_delta_mean'] = 0.0
            f['hm_checksum_delta_std']  = 0.0
    else:
        f['hm_checksum_entropy']    = 0.0
        f['hm_checksum_delta_mean'] = 0.0
        f['hm_checksum_delta_std']  = 0.0

    # IP Identification field
    if 'ip_id' in grp.columns:
        ip_ids = grp['ip_id'].dropna()
        ip_ids_int = ip_ids.apply(
            lambda x: int(str(x).replace('0x',''), 16) if str(x).startswith('0x') else 0)
        f['hm_ip_id_entropy']    = safe_entropy(ip_ids_int)
        if len(ip_ids_int) > 1:
            d = np.diff(ip_ids_int.values.astype(float))
            f['hm_ip_id_delta_mean'] = float(np.mean(np.abs(d)))
            f['hm_ip_id_reuse_rate'] = float(
                1 - len(np.unique(ip_ids_int)) / len(ip_ids_int))
        else:
            f['hm_ip_id_delta_mean'] = 0.0
            f['hm_ip_id_reuse_rate'] = 0.0
    else:
        f['hm_ip_id_entropy']    = 0.0
        f['hm_ip_id_delta_mean'] = 0.0
        f['hm_ip_id_reuse_rate'] = 0.0

    # IP Flags anomaly
    if 'ip_flags' in grp.columns:
        flags = grp['ip_flags'].astype(str)
        f['hm_flag_anomaly_ratio'] = float((flags != '0x00').sum() / n)
    else:
        f['hm_flag_anomaly_ratio'] = 0.0

    # Fragment offset
    if 'frag_offset' in grp.columns:
        fo = pd.to_numeric(grp['frag_offset'], errors='coerce').fillna(0)
        f['hm_frag_nonzero_ratio'] = float((fo > 0).sum() / n)
    else:
        f['hm_frag_nonzero_ratio'] = 0.0

    # DSCP/ToS field
    if 'dscp' in grp.columns:
        dscp = grp['dscp'].astype(str)
        f['hm_dscp_anomaly_ratio'] = float((dscp != 'Default').sum() / n)
    else:
        f['hm_dscp_anomaly_ratio'] = 0.0

    # Sequence number features
    if len(seqs) > 1:
        sd = np.diff(seqs)
        f['hm_seq_increment_std']   = float(np.std(sd))
        f['hm_seq_entropy']         = safe_entropy(seqs)
        f['hm_seq_jump_count']      = int(np.sum(sd != 1))
        f['hm_seq_monotone_ratio']  = float(np.sum(sd > 0) / len(sd))
        f['hm_seq_autocorr_lag1']   = float(np.corrcoef(seqs[:-1], seqs[1:])[0,1]) \
                                      if len(seqs) > 2 else 0.0
    else:
        f['hm_seq_increment_std']  = 0.0
        f['hm_seq_entropy']        = 0.0
        f['hm_seq_jump_count']     = 0
        f['hm_seq_monotone_ratio'] = 0.0
        f['hm_seq_autocorr_lag1']  = 0.0

    # Sequence BE vs LE correlation (covert signal if they differ)
    if 'icmp_seq_le' in grp.columns:
        seq_le = grp['icmp_seq_le'].dropna().values.astype(float)
        ml = min(len(seqs), len(seq_le))
        if ml > 2:
            try:
                c = np.corrcoef(seqs[:ml], seq_le[:ml])[0, 1]
                f['hm_seq_be_le_corr'] = float(c) if not np.isnan(c) else 1.0
            except:
                f['hm_seq_be_le_corr'] = 1.0
        else:
            f['hm_seq_be_le_corr'] = 1.0
    else:
        f['hm_seq_be_le_corr'] = 1.0

    # ICMP ID features
    if len(ids) > 1:
        f['hm_id_reuse_rate']  = float(1 - len(np.unique(ids)) / len(ids))
        f['hm_id_entropy']     = safe_entropy(ids)
        id_d = np.diff(ids)
        f['hm_id_delta_mean']  = float(np.mean(np.abs(id_d)))
        f['hm_id_delta_std']   = float(np.std(id_d))
        ml = min(len(ids), len(seqs))
        if ml > 2:
            try:
                c = np.corrcoef(ids[:ml], seqs[:ml])[0, 1]
                f['hm_id_seq_corr'] = float(c) if not np.isnan(c) else 0.0
            except:
                f['hm_id_seq_corr'] = 0.0
        else:
            f['hm_id_seq_corr'] = 0.0
    else:
        f['hm_id_reuse_rate'] = 0.0
        f['hm_id_entropy']    = 0.0
        f['hm_id_delta_mean'] = 0.0
        f['hm_id_delta_std']  = 0.0
        f['hm_id_seq_corr']   = 0.0

    f['hm_covert_id_count'] = int(grp['icmp_id'].apply(
        lambda x: 1 if (pd.notna(x) and int(x) in COVERT_IDS) else 0).sum())

    # Payload length features
    f['hm_payload_len_mean']       = float(np.mean(pld))
    f['hm_payload_len_std']        = float(np.std(pld))
    f['hm_payload_len_entropy']    = safe_entropy(pld)
    f['hm_payload_len_variance']   = float(np.var(pld))
    mode_p = float(stats.mode(pld, keepdims=True).mode[0])
    f['hm_non_std_payload_ratio']  = float(np.sum(pld != mode_p) / n)

    # Raw payload byte features (File1 only — has Data column)
    if has_raw_payload and 'payload_hex' in grp.columns:
        pf = payload_byte_features(grp['payload_hex'])
    else:
        pf = {
            'pld_byte_entropy_mean': np.nan,    'pld_byte_entropy_std': np.nan,
            'pld_compress_ratio_mean': np.nan,  'pld_compress_ratio_std': np.nan,
            'pld_printable_ratio_mean': np.nan, 'pld_printable_ratio_std': np.nan,
            'pld_null_ratio_mean': np.nan,      'pld_null_ratio_std': np.nan,
            'pld_bigram_entropy_mean': np.nan,  'pld_bigram_entropy_std': np.nan,
        }
    f.update(pf)

    # ── FLOW BLENDING FEATURES ────────────────────────────────────────

    f['fb_packet_count']      = n
    f['fb_byte_count']        = float(lens.sum())
    f['fb_flow_duration']     = float(times[-1] - times[0]) if n > 1 else 0.0
    f['fb_pps']               = n / f['fb_flow_duration'] if f['fb_flow_duration'] > 0 else 0.0
    f['fb_bps']               = f['fb_byte_count'] / f['fb_flow_duration'] \
                                if f['fb_flow_duration'] > 0 else 0.0

    # Request/reply symmetry
    f['fb_echo_req_count']    = len(req)
    f['fb_echo_rep_count']    = len(rep)
    f['fb_req_reply_ratio']   = len(req) / max(len(rep), 1)
    f['fb_orphan_req_ratio']  = len(req) / n
    f['fb_orphan_rep_ratio']  = len(rep) / n
    req_bytes = float(req['length'].sum()) if len(req) else 0.0
    rep_bytes = float(rep['length'].sum()) if len(rep) else 0.0
    f['fb_byte_asymmetry']    = req_bytes / max(rep_bytes, 1.0)

    # TTL consistency
    f['fb_ttl_mean']         = float(np.mean(ttls)) if len(ttls) > 0 else np.nan
    f['fb_ttl_std']          = float(np.std(ttls))  if len(ttls) > 0 else np.nan
    ttl_cv = f['fb_ttl_std'] / f['fb_ttl_mean'] \
             if (len(ttls) > 0 and f['fb_ttl_mean'] and f['fb_ttl_mean'] > 0) else 0.0
    f['fb_ttl_consistency']  = 1.0 - min(ttl_cv, 1.0)

    # Packet size distribution
    f['fb_pkt_size_mean']    = float(np.mean(lens))
    f['fb_pkt_size_std']     = float(np.std(lens))
    f['fb_pkt_size_min']     = float(np.min(lens))
    f['fb_pkt_size_max']     = float(np.max(lens))
    f['fb_pkt_size_median']  = float(np.median(lens))
    f['fb_pkt_size_entropy'] = safe_entropy(lens)
    f['fb_pkt_size_skew']    = float(stats.skew(lens))     if n > 2 else 0.0
    f['fb_pkt_size_kurt']    = float(stats.kurtosis(lens)) if n > 2 else 0.0
    f['fb_pkt_size_cv']      = float(np.std(lens) / np.mean(lens)) \
                               if np.mean(lens) > 0 else 0.0
    f['fb_pkt_size_iqr']     = float(np.percentile(lens, 75) - np.percentile(lens, 25))

    # Packet size histogram (8 bins: 60–1442 bytes)
    bin_edges = np.linspace(60, 1442, 9)
    hist, _   = np.histogram(lens, bins=bin_edges)
    for i, h in enumerate(hist):
        f[f'fb_size_bin_{i}'] = float(h / n)

    # Size transition matrix (4×4)
    bin_idx = np.digitize(lens, np.linspace(60, 1442, 5)).clip(1, 4) - 1
    for i in range(4):
        for j in range(4):
            f[f'fb_size_trans_{i}{j}'] = float(
                ((bin_idx[:-1] == i) & (bin_idx[1:] == j)).sum() / max(n - 1, 1))

    mode_l = float(stats.mode(lens, keepdims=True).mode[0])
    f['fb_uniform_size_ratio'] = float(np.sum(lens == mode_l) / n)
    f['fb_kl_div_baseline']    = kl_divergence(lens)

    # Frame length vs capture length (truncation)
    if 'frame_len' in grp.columns and 'cap_len' in grp.columns:
        fl = pd.to_numeric(grp['frame_len'], errors='coerce')
        cl = pd.to_numeric(grp['cap_len'],   errors='coerce')
        diff = (fl - cl).dropna()
        f['fb_truncation_ratio'] = float((diff > 0).sum() / max(len(diff), 1))
    else:
        f['fb_truncation_ratio'] = 0.0

    # ── TIME OBFUSCATION FEATURES ─────────────────────────────────────

    f['to_ipt_mean']    = float(np.mean(ipt))
    f['to_ipt_std']     = float(np.std(ipt))
    f['to_ipt_min']     = float(np.min(ipt))
    f['to_ipt_max']     = float(np.max(ipt))
    f['to_ipt_median']  = float(np.median(ipt))
    f['to_ipt_q90']     = float(np.percentile(ipt, 90))
    f['to_ipt_q99']     = float(np.percentile(ipt, 99))
    f['to_ipt_entropy'] = safe_entropy(ipt)
    f['to_ipt_skew']    = float(stats.skew(ipt))     if len(ipt) > 2 else 0.0
    f['to_ipt_kurt']    = float(stats.kurtosis(ipt)) if len(ipt) > 2 else 0.0
    f['to_ipt_cv']      = float(np.std(ipt) / np.mean(ipt)) if np.mean(ipt) > 0 else 0.0
    f['to_ipt_iqr']     = float(np.percentile(ipt, 75) - np.percentile(ipt, 25))

    # IPT autocorrelation lags 1–10
    for lag in range(1, 11):
        if len(ipt) > lag + 1:
            try:
                ac = np.corrcoef(ipt[:-lag], ipt[lag:])[0, 1]
                f[f'to_ipt_ac_{lag}'] = float(ac) if not np.isnan(ac) else 0.0
            except:
                f[f'to_ipt_ac_{lag}'] = 0.0
        else:
            f[f'to_ipt_ac_{lag}'] = 0.0

    # FFT top-5 dominant frequencies
    if len(ipt) >= 8:
        arr2 = np.asarray(ipt, dtype=float) - np.mean(ipt)
        spec = np.abs(rfft(arr2)) ** 2
        top5 = np.argsort(spec[1:])[-5:][::-1] + 1
        for i, fi in enumerate(top5):
            f[f'to_fft_freq_{i}'] = float(fi)
            f[f'to_fft_mag_{i}']  = float(spec[fi])
    else:
        for i in range(5):
            f[f'to_fft_freq_{i}'] = 0.0
            f[f'to_fft_mag_{i}']  = 0.0

    f['to_periodic_score'] = periodicity_score(ipt)

    # Burst analysis
    burst_n, burst_s, ibis = burst_analysis(times)
    f['to_burst_count']     = burst_n
    f['to_burst_size_mean'] = float(np.mean(burst_s))
    f['to_burst_size_std']  = float(np.std(burst_s))  if len(burst_s) > 1 else 0.0
    f['to_burst_size_max']  = float(np.max(burst_s))
    f['to_ibi_mean']        = float(np.mean(ibis)) if ibis else 0.0
    f['to_ibi_std']         = float(np.std(ibis))  if ibis else 0.0
    f['to_ibi_entropy']     = safe_entropy(ibis)   if ibis else 0.0

    # Idle periods
    idle_n, idle_d = idle_periods(times)
    f['to_idle_count']    = idle_n
    f['to_idle_dur_mean'] = float(np.mean(idle_d)) if idle_d else 0.0
    f['to_idle_dur_max']  = float(np.max(idle_d))  if idle_d else 0.0

    # Timing regularity (autocorrelation of IPT at lag-1)
    if len(ipt) > 2:
        try:
            ac = np.corrcoef(ipt[:-1], ipt[1:])[0, 1]
            f['to_timing_regularity'] = float(ac) if not np.isnan(ac) else 0.0
        except:
            f['to_timing_regularity'] = 0.0
    else:
        f['to_timing_regularity'] = 0.0

    # Jitter
    jit = np.abs(ipt - np.mean(ipt))
    f['to_jitter_mean']    = float(np.mean(jit))
    f['to_jitter_std']     = float(np.std(jit))
    f['to_jitter_entropy'] = safe_entropy(jit)

    # Clock skew (linear fit of seq vs time)
    f['to_clock_skew'] = np.nan
    if len(seqs) > 2:
        try:
            s, _ = np.polyfit(times[:len(seqs)], seqs, 1)
            f['to_clock_skew'] = float(s)
        except:
            pass

    # RTT estimation (request → nearest reply)
    rtts = []
    if len(req) > 0 and len(rep) > 0:
        for rt in req['time'].values:
            cands = rep['time'].values[rep['time'].values > rt]
            if len(cands) > 0:
                rtts.append(float(cands[0] - rt))
    f['to_rtt_mean']    = float(np.mean(rtts))    if rtts else np.nan
    f['to_rtt_std']     = float(np.std(rtts))     if rtts else np.nan
    f['to_rtt_entropy'] = safe_entropy(rtts)       if rtts else 0.0
    f['to_rtt_anomaly'] = f['to_rtt_std'] / f['to_rtt_mean'] \
                         if (rtts and f['to_rtt_mean'] and f['to_rtt_mean'] > 0) else 0.0

    return f

# ══════════════════════════════════════════════════════════════════════
# LOAD & STANDARDISE BOTH FILES
# ══════════════════════════════════════════════════════════════════════

def load_and_standardise(path, encoding='latin1'):
    print(f"  Loading {path} ...")
    df = pd.read_csv(path, encoding=encoding)
    df.columns = [c.strip().strip('"') for c in df.columns]

    # Standard renames
    rename = {
        'No.':                              'pkt_no',
        'Time':                             'time',
        'Source':                           'src',
        'Destination':                      'dst',
        'Length':                           'length',
        'Info':                             'info',
        'Checksum':                         'checksum_hex',      # ICMP checksum hex
        'Identifier (BE)':                  'icmp_id_be',
        'Identifier (LE)':                  'icmp_id_le',
        'Checksum Status':                  'chk_status',
        'Sequence Number (BE)':             'seq_be',
        'Sequence Number (LE)':             'icmp_seq_le',
        'Identification':                   'ip_id',             # IP identification
        'Flags':                            'ip_flags',
        'Fragment Offset':                  'frag_offset',
        'Differentiated Services Codepoint':'dscp',
        'Explicit Congestion Notification': 'ecn',
        'Type.1':                           'icmp_type_raw',     # ICMP type string
        'Code':                             'icmp_code',
        'Data':                             'payload_hex',       # raw payload bytes
        'Frame Length':                     'frame_len',
        'Capture Length':                   'cap_len',
        'Length.1':                         'data_len',
    }
    df = df.rename(columns={k: v for k, v in rename.items() if k in df.columns})

    df['time']   = pd.to_numeric(df['time'],   errors='coerce')
    df['length'] = pd.to_numeric(df['length'], errors='coerce')
    df = df.dropna(subset=['time', 'length']).reset_index(drop=True)

    # Parse Info field
    parsed        = df['info'].apply(parse_info)
    df['msg_type']= [p[0] for p in parsed]
    df['icmp_id'] = pd.array([p[1] for p in parsed], dtype='Float64')
    df['icmp_seq']= pd.array([p[2] for p in parsed], dtype='Float64')
    df['ttl']     = pd.array([p[3] for p in parsed], dtype='Float64')

    # Use Identifier (BE) as icmp_id if Info parse failed
    if 'icmp_id_be' in df.columns:
        df['icmp_id'] = df['icmp_id'].fillna(df['icmp_id_be'])
    if 'seq_be' in df.columns:
        df['icmp_seq'] = df['icmp_seq'].fillna(df['seq_be'])

    print(f"    {len(df):,} packets | "
          f"TTL dist: {df['ttl'].value_counts().to_dict()}")
    return df

print("="*60)
print("ICMP FLOW FEATURE EXTRACTOR")
print("="*60)

print("\n[1] Loading packet-level files ...")
df1 = load_and_standardise(FILE1)
df2 = load_and_standardise(FILE2)

# Mark source so we know which has raw payload / checksum
df1['_has_payload']  = True
df1['_has_checksum'] = True
df2['_has_payload']  = False
df2['_has_checksum'] = True   # File2 also has Checksum Status

# Combine
df_all = pd.concat([df1, df2], ignore_index=True)
df_all['time'] = pd.to_numeric(df_all['time'], errors='coerce')
df_all = df_all.dropna(subset=['time', 'length', 'ttl']).reset_index(drop=True)
df_all['ttl_int'] = df_all['ttl'].astype(int)

print(f"\n[2] Combined: {len(df_all):,} packets total")
print(f"    TTL distribution: {df_all['ttl_int'].value_counts().to_dict()}")

# ══════════════════════════════════════════════════════════════════════
# SLIDING WINDOW FLOW EXTRACTION
# ══════════════════════════════════════════════════════════════════════

print(f"\n[3] Extracting flows (window={WINDOW_SEC}s, step={STEP_SEC}s) ...")

records = []

for ttl_val, label in TTL_LABEL.items():
    sub = df_all[df_all['ttl_int'] == ttl_val].sort_values('time').reset_index(drop=True)
    if len(sub) == 0:
        print(f"    TTL={ttl_val}: no packets found")
        continue

    t0, t1  = sub['time'].min(), sub['time'].max()
    windows = np.arange(t0, t1 - WINDOW_SEC + 0.001, STEP_SEC)
    win_count = 0

    for ws in windows:
        we     = ws + WINDOW_SEC
        window = sub[(sub['time'] >= ws) & (sub['time'] < we)].copy()
        if len(window) < MIN_PKTS:
            continue

        has_raw = bool(window['_has_payload'].any())
        has_chk = bool(window['_has_checksum'].any())

        feats = extract_flow_features(window,
                                      has_raw_payload=has_raw,
                                      has_checksum_col=has_chk)
        if feats is None:
            continue

        feats['label']      = label
        feats['label_name'] = LABEL_NAME[label]
        feats['ttl_group']  = ttl_val
        feats['win_start']  = round(ws, 3)
        records.append(feats)
        win_count += 1

    print(f"    TTL={ttl_val} ({LABEL_NAME[label]}): {win_count} flows")

# ══════════════════════════════════════════════════════════════════════
# BALANCE TO FLOWS_PER_CLASS
# ══════════════════════════════════════════════════════════════════════

df_flows = pd.DataFrame(records)

print(f"\n[4] Before balancing:")
print(df_flows['label_name'].value_counts().to_string())

balanced = []
for label in sorted(TTL_LABEL.values()):
    cls = df_flows[df_flows['label'] == label]
    if len(cls) == 0:
        print(f"    WARNING: No flows for label {label}")
        continue
    n_sample = min(len(cls), FLOWS_PER_CLASS)
    balanced.append(cls.sample(n=n_sample, random_state=RANDOM_SEED))

df_balanced = pd.concat(balanced, ignore_index=True).sample(
    frac=1, random_state=RANDOM_SEED).reset_index(drop=True)

# Fill NaN payload features (classes without raw bytes) with column median
num_cols = df_balanced.select_dtypes(include='number').columns
for col in num_cols:
    if df_balanced[col].isna().any():
        median_val = df_balanced[col].median()
        df_balanced[col] = df_balanced[col].fillna(median_val)

# ══════════════════════════════════════════════════════════════════════
# SAVE
# ══════════════════════════════════════════════════════════════════════

df_balanced.to_csv(OUTPUT_CSV, index=False)

feat_cols = [c for c in df_balanced.columns
             if c not in ('label', 'label_name', 'ttl_group', 'win_start')]

print(f"\n{'='*60}")
print(f"[✓] Saved → {OUTPUT_CSV}")
print(f"    Flows:    {len(df_balanced):,}")
print(f"    Features: {len(feat_cols)}")
print(f"\nFinal class distribution:")
print(df_balanced['label_name'].value_counts().to_string())
print(f"\nFeature groups:")
hm = [c for c in feat_cols if c.startswith('hm_')]
fb = [c for c in feat_cols if c.startswith('fb_')]
to = [c for c in feat_cols if c.startswith('to_')]
pf = [c for c in feat_cols if c.startswith('pld_')]
print(f"  Header Manipulation (hm_*): {len(hm)} features")
print(f"  Flow Blending       (fb_*): {len(fb)} features")
print(f"  Time Obfuscation    (to_*): {len(to)} features")
print(f"  Payload Bytes       (pld_): {len(pf)} features")
print(f"  TOTAL:                      {len(hm)+len(fb)+len(to)+len(pf)} features")

============================================================
ICMP FLOW FEATURE EXTRACTOR
============================================================

[1] Loading packet-level files ...
  Loading /content/ICMP-PACKET1ST-FINAL.csv ...
    100,056 packets | TTL dist: {np.float64(64.0): 82502, np.float64(255.0): 9200, np.float64(128.0): 7286}
  Loading /content/ICMP-PACKETLEVEL2ND-FINAL.csv ...
    100,000 packets | TTL dist: {np.float64(64.0): 82884, np.float64(255.0): 8869, np.float64(128.0): 7207}

[2] Combined: 197,948 packets total
    TTL distribution: {64: 165386, 255: 18069, 128: 14493}

[3] Extracting flows (window=5.0s, step=2.5s) ...
    TTL=64 (Header_Manipulation): 1174 flows
    TTL=128 (Flow_Blending): 81 flows
    TTL=255 (Time_Obfuscation): 81 flows

[4] Before balancing:
label_name
Header_Manipulation    1174
Flow_Blending            81
Time_Obfuscation         81

============================================================
[✓] Saved → icmp_flow_features_final.csv
    Flows:    662
    Features: 148

Final class distribution:
label_name
Header_Manipulation    500
Flow_Blending           81
Time_Obfuscation        81

Feature groups:
  Header Manipulation (hm_*): 35 features
  Flow Blending       (fb_*): 51 features
  Time Obfuscation    (to_*): 52 features
  Payload Bytes       (pld_): 10 features
  TOTAL:                      148 features

In [ ]:
"""
ICMP Covert Channel — Feature Selection, Balancing & Transformer-Ready Export
==============================================================================
Steps:
  1. Load flow-level CSV
  2. Drop dead / zero-variance / null features
  3. Drop low-discriminating features (F-score < 5)
  4. Keep only covert-relevant features per technique group
  5. Balance classes using SMOTE (synthetic minority oversampling)
  6. Standardise features (StandardScaler) for transformer input
  7. Save: balanced CSV + scaled numpy arrays (.npy) + feature list

Output files:
  icmp_covert_balanced.csv        — balanced, cleaned, unscaled  (for inspection)
  icmp_covert_scaled.npy          — scaled feature matrix  X  (for transformer)
  icmp_covert_labels.npy          — label vector            y
  icmp_covert_feature_names.txt   — ordered feature names
  icmp_covert_label_map.txt       — label → class name mapping

Usage:
  python balance_and_prepare.py

  # In Colab:
  INPUT_CSV = "/content/icmp_flow_features_final.csv"
"""

import numpy as np
import pandas as pd
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

# ── CONFIG ────────────────────────────────────────────────────────────────────
INPUT_CSV   = "/content/icmp_flow_features_final.csv"
OUT_CSV     = "icmp_covert_balanced.csv"
OUT_X_NPY   = "icmp_covert_scaled.npy"
OUT_Y_NPY   = "icmp_covert_labels.npy"
OUT_FEATS   = "icmp_covert_feature_names.txt"
OUT_LABELS  = "icmp_covert_label_map.txt"

TARGET_PER_CLASS = 500   # final flows per class after SMOTE
F_THRESHOLD      = 5.0   # minimum ANOVA F-score to keep a feature
RANDOM_SEED      = 42
np.random.seed(RANDOM_SEED)

LABEL_MAP = {0: "Header_Manipulation", 1: "Flow_Blending", 2: "Time_Obfuscation"}

# ── LOAD ──────────────────────────────────────────────────────────────────────
print("="*65)
print("ICMP COVERT CHANNEL — FEATURE SELECTION + BALANCING PIPELINE")
print("="*65)

df = pd.read_csv(INPUT_CSV)
print(f"\n[1] Loaded: {df.shape[0]} flows × {df.shape[1]} columns")
print(f"    Class distribution:")
for l, name in LABEL_MAP.items():
    print(f"      {name}: {(df['label']==l).sum()}")

META_COLS = ['label', 'label_name', 'ttl_group', 'win_start']
feat_cols = [c for c in df.columns if c not in META_COLS]
print(f"\n    Raw feature count: {len(feat_cols)}")

# ── STEP 1: DROP DEAD FEATURES ────────────────────────────────────────────────
print("\n[2] Dropping dead / null features ...")

dead_zero_var = [c for c in feat_cols
                 if df[c].std() == 0 or df[c].nunique() <= 1]
all_null      = [c for c in feat_cols if df[c].isna().all()]
dead          = list(set(dead_zero_var + all_null))

print(f"    Zero-variance: {len(dead_zero_var)}")
print(f"    All-null:      {len(all_null)}")
print(f"    Dropped:       {dead}")

feat_cols = [c for c in feat_cols if c not in dead]
print(f"    Remaining:     {len(feat_cols)}")

# ── STEP 2: DROP LOW F-SCORE FEATURES ────────────────────────────────────────
print(f"\n[3] Computing ANOVA F-scores (threshold = {F_THRESHOLD}) ...")

f_scores = {}
for c in feat_cols:
    try:
        groups = [df[df['label'] == l][c].dropna().values for l in LABEL_MAP]
        if all(len(g) > 1 for g in groups):
            f, _ = stats.f_oneway(*groups)
            f_scores[c] = float('inf') if np.isinf(f) else (0.0 if np.isnan(f) else float(f))
    except:
        f_scores[c] = 0.0

low_f     = [c for c in feat_cols if f_scores.get(c, 0) < F_THRESHOLD]
feat_cols = [c for c in feat_cols if f_scores.get(c, 0) >= F_THRESHOLD]

print(f"    Dropped (F < {F_THRESHOLD}): {len(low_f)}")
print(f"    Dropped features: {sorted(low_f)}")
print(f"    Remaining:        {len(feat_cols)}")

# ── STEP 3: COVERT-RELEVANCE FILTER ──────────────────────────────────────────
# Keep features that are theoretically meaningful for covert detection.
# Remove any remaining features that are redundant or non-informative
# for the three technique categories.
print("\n[4] Applying covert-relevance filter ...")

# Explicitly define which features are RELEVANT per technique
# (based on F-score analysis + domain knowledge of ICMP covert channels)

COVERT_RELEVANT = {

    # ── HEADER MANIPULATION ──────────────────────────────────────────────────
    # Captures: type/code abuse, checksum tampering, ID/seq anomalies,
    #           payload stuffing, covert ID markers
    "hm_type_code_entropy",      # entropy of ICMP type-code combinations
    "hm_invalid_type_ratio",     # fraction of non-echo ICMP types
    "hm_non_echo_ratio",         # fraction not echo request/reply
    "hm_icmp_type_diversity",    # diversity of ICMP type strings
    "hm_nonstandard_type_count", # count of non-standard ICMP types
    "hm_code_entropy",           # entropy of ICMP code field
    "hm_nonzero_code_ratio",     # non-zero codes = misuse
    "hm_bad_checksum_ratio",     # bad checksums = direct manipulation signal
    "hm_good_checksum_ratio",    # inverse of above
    "hm_checksum_entropy",       # entropy of checksum values
    "hm_checksum_delta_mean",    # mean change between consecutive checksums
    "hm_checksum_delta_std",     # std of checksum deltas
    "hm_ip_id_reuse_rate",       # IP ID reuse (covert tools recycle IDs)
    "hm_seq_increment_std",      # non-monotonic seq increments
    "hm_seq_entropy",            # randomness of sequence numbers
    "hm_seq_monotone_ratio",     # fraction of monotone seq increments
    "hm_seq_autocorr_lag1",      # autocorrelation of seq series
    "hm_id_reuse_rate",          # ICMP ID reuse across flow
    "hm_id_entropy",             # entropy of ICMP IDs
    "hm_id_delta_mean",          # mean ID delta
    "hm_id_delta_std",           # std of ID deltas
    "hm_id_seq_corr",            # correlation between ID and seq (tool fingerprint)
    "hm_covert_id_count",        # count of known covert IDs (0xDEAD etc.)
    "hm_payload_len_mean",       # mean payload size
    "hm_payload_len_std",        # std of payload sizes
    "hm_payload_len_entropy",    # entropy of payload length distribution
    "hm_payload_len_variance",   # variance of payload lengths
    "hm_non_std_payload_ratio",  # fraction deviating from standard ping payload
    # Raw payload byte features (from File1)
    "pld_byte_entropy_mean",     # mean byte entropy across flow packets
    "pld_byte_entropy_std",
    "pld_compress_ratio_mean",   # low ratio = encrypted/random data
    "pld_compress_ratio_std",
    "pld_printable_ratio_mean",  # high ratio = text-based covert channel
    "pld_printable_ratio_std",
    "pld_null_ratio_mean",       # null byte stuffing
    "pld_null_ratio_std",
    "pld_bigram_entropy_mean",   # bigram entropy (byte-pair patterns)
    "pld_bigram_entropy_std",

    # ── FLOW BLENDING ────────────────────────────────────────────────────────
    # Captures: traffic volume mimicry, size distribution, rate patterns,
    #           request/reply asymmetry, deviation from normal ICMP baseline
    "fb_byte_count",             # total bytes in flow
    "fb_flow_duration",          # flow window duration
    "fb_bps",                    # bytes per second
    "fb_orphan_req_ratio",       # requests without replies (covert = all requests)
    "fb_byte_asymmetry",         # req/reply byte ratio
    "fb_ttl_mean",               # TTL value (tool fingerprint)
    "fb_pkt_size_mean",          # mean packet size
    "fb_pkt_size_std",           # std of packet sizes
    "fb_pkt_size_max",           # max packet size (covert tools use large packets)
    "fb_pkt_size_median",        # median packet size
    "fb_pkt_size_entropy",       # entropy of size distribution
    "fb_pkt_size_skew",          # skewness of size distribution
    "fb_pkt_size_kurt",          # kurtosis of size distribution
    "fb_pkt_size_cv",            # coefficient of variation of sizes
    "fb_pkt_size_iqr",           # interquartile range of sizes
    "fb_size_bin_0",             # fraction in size bin 60-240B
    "fb_size_bin_1",             # fraction in size bin 240-420B
    "fb_size_bin_2",             # fraction in size bin 420-600B
    "fb_size_bin_3",             # fraction in size bin 600-780B
    "fb_size_bin_4",             # fraction in size bin 780-960B
    "fb_size_bin_5",             # fraction in size bin 960-1140B
    "fb_size_bin_6",             # fraction in size bin 1140-1320B
    "fb_size_bin_7",             # fraction in size bin 1320-1442B
    "fb_size_trans_00",          # size transition matrix (small→small)
    "fb_size_trans_01",          # size transition (small→medium)
    "fb_size_trans_02",
    "fb_size_trans_03",          # size transition (small→large)
    "fb_size_trans_10",
    "fb_size_trans_11",
    "fb_size_trans_12",
    "fb_size_trans_13",
    "fb_size_trans_20",
    "fb_size_trans_21",
    "fb_size_trans_22",
    "fb_size_trans_23",
    "fb_size_trans_30",          # size transition (large→small = suspicious)
    "fb_size_trans_31",
    "fb_size_trans_32",
    "fb_size_trans_33",
    "fb_uniform_size_ratio",     # fraction with uniform/fixed size
    "fb_kl_div_baseline",        # KL divergence from normal ping distribution

    # ── TIME OBFUSCATION ─────────────────────────────────────────────────────
    # Captures: inter-packet timing manipulation, regularity/irregularity,
    #           periodicity, jitter patterns
    "to_ipt_mean",               # mean inter-packet time
    "to_ipt_std",                # std of IPT
    "to_ipt_min",                # minimum IPT
    "to_ipt_max",                # maximum IPT
    "to_ipt_median",             # median IPT
    "to_ipt_q90",                # 90th percentile IPT
    "to_ipt_q99",                # 99th percentile IPT
    "to_ipt_entropy",            # entropy of IPT distribution
    "to_ipt_skew",               # skewness of IPT
    "to_ipt_cv",                 # coefficient of variation (regularity)
    "to_ipt_iqr",                # IQR of IPT
    "to_ipt_ac_1",               # autocorrelation lag-1 (timing pattern)
    "to_ipt_ac_2",               # autocorrelation lag-2
    "to_ipt_ac_3",               # autocorrelation lag-3
    "to_periodic_score",         # FFT-based periodicity score
    "to_timing_regularity",      # lag-1 autocorrelation (regularity detector)
    "to_jitter_mean",            # mean absolute jitter
    "to_jitter_std",             # std of jitter
}

# Intersect with surviving features (after dead + F-score drops)
feat_cols_final = [c for c in feat_cols if c in COVERT_RELEVANT]

# Also keep any high-F feature not in explicit set (safety net)
extra_high_f = [c for c in feat_cols
                if c not in COVERT_RELEVANT
                and f_scores.get(c, 0) >= 50
                and c not in feat_cols_final]

feat_cols_final = feat_cols_final + extra_high_f

print(f"    Covert-relevant kept: {len([c for c in feat_cols if c in COVERT_RELEVANT])}")
print(f"    Extra high-F added:   {len(extra_high_f)}")
print(f"    Final feature count:  {len(feat_cols_final)}")
print()
for prefix, name in [('hm_','Header Manipulation'),('pld_','Payload Bytes'),
                      ('fb_','Flow Blending'),('to_','Time Obfuscation')]:
    cnt = len([c for c in feat_cols_final if c.startswith(prefix)])
    print(f"    {name}: {cnt} features")

# ── STEP 4: BUILD CLEAN DATASET ───────────────────────────────────────────────
print("\n[5] Building clean feature matrix ...")

X_df = df[feat_cols_final].copy()
y    = df['label'].values.astype(int)

# Fill any remaining NaN with column median (pld_* features are NaN for File2)
for col in X_df.columns:
    if X_df[col].isna().any():
        med = X_df[col].median()
        X_df[col] = X_df[col].fillna(med if not np.isnan(med) else 0.0)

X = X_df.values.astype(np.float32)
print(f"    X shape: {X.shape}")
print(f"    y shape: {y.shape}")
print(f"    Any NaN: {np.isnan(X).any()}")

# ── STEP 5: SMOTE ─────────────────────────────────────────────────────────────
print("\n[6] Applying SMOTE to balance classes ...")

def smote(X, y, target_per_class, k=5, seed=42):
    """
    Synthetic Minority Oversampling Technique (SMOTE).
    For each minority class, generates synthetic samples by interpolating
    between real samples and their k nearest neighbours.
    """
    rng = np.random.default_rng(seed)
    classes = np.unique(y)
    X_out, y_out = [X.copy()], [y.copy()]

    for cls in classes:
        X_cls = X[y == cls]
        n_have   = len(X_cls)
        n_needed = target_per_class - n_have
        if n_needed <= 0:
            # Undersample majority class
            idx = rng.choice(n_have, target_per_class, replace=False)
            # Replace X_out[0] entries for this class
            continue

        synthetic = []
        k_actual  = min(k, n_have - 1)

        for _ in range(n_needed):
            # Pick a random seed sample
            idx = rng.integers(0, n_have)
            sample = X_cls[idx]

            # Find k nearest neighbours (Euclidean)
            dists = np.sum((X_cls - sample) ** 2, axis=1)
            dists[idx] = np.inf   # exclude self
            nn_idx = np.argpartition(dists, k_actual)[:k_actual]

            # Pick one neighbour at random
            neighbour = X_cls[rng.choice(nn_idx)]

            # Interpolate
            alpha = rng.random()
            synthetic.append(sample + alpha * (neighbour - sample))

        X_out.append(np.array(synthetic, dtype=np.float32))
        y_out.append(np.full(n_needed, cls, dtype=int))

    X_bal = np.vstack(X_out)
    y_bal = np.concatenate(y_out)
    return X_bal, y_bal

# First undersample majority class to TARGET_PER_CLASS
# then SMOTE minority classes up to TARGET_PER_CLASS
rng = np.random.default_rng(RANDOM_SEED)

X_parts, y_parts = [], []
for cls in sorted(LABEL_MAP.keys()):
    idx_cls = np.where(y == cls)[0]
    n       = len(idx_cls)
    if n >= TARGET_PER_CLASS:
        # Undersample
        chosen = rng.choice(idx_cls, TARGET_PER_CLASS, replace=False)
        X_parts.append(X[chosen])
        y_parts.append(y[chosen])
    else:
        # Keep all real + SMOTE up to target
        X_cls = X[idx_cls]
        n_need = TARGET_PER_CLASS - n
        k_actual = min(5, n - 1)
        synthetic = []
        for _ in range(n_need):
            i = rng.integers(0, n)
            sample = X_cls[i]
            dists  = np.sum((X_cls - sample) ** 2, axis=1)
            dists[i] = np.inf
            nn_idx = np.argpartition(dists, k_actual)[:k_actual]
            neighbour = X_cls[rng.choice(nn_idx)]
            alpha = rng.random()
            synthetic.append((sample + alpha * (neighbour - sample))
                             .astype(np.float32))
        X_parts.append(np.vstack([X_cls,
                                   np.array(synthetic, dtype=np.float32)]))
        y_parts.append(np.full(TARGET_PER_CLASS, cls, dtype=int))
        print(f"    Class {cls} ({LABEL_MAP[cls]}): "
              f"{n} real + {n_need} synthetic = {TARGET_PER_CLASS}")

X_bal = np.vstack(X_parts)
y_bal = np.concatenate(y_parts)

# Shuffle
shuffle_idx = rng.permutation(len(y_bal))
X_bal = X_bal[shuffle_idx]
y_bal = y_bal[shuffle_idx]

print(f"\n    Balanced dataset: {X_bal.shape}")
for cls, name in LABEL_MAP.items():
    print(f"      {name}: {(y_bal==cls).sum()}")

# ── STEP 6: STANDARDISE ───────────────────────────────────────────────────────
print("\n[7] Standardising features (zero mean, unit variance) ...")

mean = X_bal.mean(axis=0)
std  = X_bal.std(axis=0)
std[std == 0] = 1.0       # avoid divide-by-zero for any remaining constant cols
X_scaled = (X_bal - mean) / std
X_scaled  = X_scaled.astype(np.float32)

print(f"    Global mean range:  [{mean.min():.4f}, {mean.max():.4f}]")
print(f"    Global std  range:  [{std.min():.6f}, {std.max():.4f}]")
print(f"    Scaled X range:     [{X_scaled.min():.4f}, {X_scaled.max():.4f}]")
print(f"    Any NaN after scale: {np.isnan(X_scaled).any()}")

# ── STEP 7: SAVE ──────────────────────────────────────────────────────────────
print("\n[8] Saving outputs ...")

# 1. Balanced CSV (unscaled, readable)
df_bal = pd.DataFrame(X_bal, columns=feat_cols_final)
df_bal['label']      = y_bal
df_bal['label_name'] = [LABEL_MAP[l] for l in y_bal]
df_bal.to_csv(OUT_CSV, index=False)
print(f"    {OUT_CSV}: {df_bal.shape}")

# 2. Scaled numpy array for transformer
np.save(OUT_X_NPY, X_scaled)
print(f"    {OUT_X_NPY}: {X_scaled.shape}")

# 3. Labels
np.save(OUT_Y_NPY, y_bal)
print(f"    {OUT_Y_NPY}: {y_bal.shape}")

# 4. Feature names (ordered)
with open(OUT_FEATS, 'w') as f:
    for i, name in enumerate(feat_cols_final):
        f_val = f_scores.get(name, 0)
        f_str = "inf" if f_val == float('inf') else f"{f_val:.1f}"
        f.write(f"{i:3d}  {name:<45}  F={f_str}\n")
print(f"    {OUT_FEATS}: {len(feat_cols_final)} features listed")

# 5. Label map
with open(OUT_LABELS, 'w') as f:
    for k, v in LABEL_MAP.items():
        f.write(f"{k}: {v}\n")
print(f"    {OUT_LABELS}")

# ── SUMMARY ───────────────────────────────────────────────────────────────────
print(f"""
{'='*65}
PIPELINE COMPLETE — TRANSFORMER-READY DATASET
{'='*65}

  Input flows:          662  (500 HM / 81 FB / 81 TO)
  Output flows:        {len(y_bal)}  ({TARGET_PER_CLASS} per class × 3)
  Features:            {len(feat_cols_final)}
    Header Manipulation: {len([c for c in feat_cols_final if c.startswith('hm_')])} (hm_*)
    Payload Bytes:       {len([c for c in feat_cols_final if c.startswith('pld_')])} (pld_*)
    Flow Blending:       {len([c for c in feat_cols_final if c.startswith('fb_')])} (fb_*)
    Time Obfuscation:    {len([c for c in feat_cols_final if c.startswith('to_')])} (to_*)

  Dropped features:
    Dead/zero-variance:  {len(dead)}
    Low F-score (<{F_THRESHOLD}):   {len(low_f)}
    Not covert-relevant: {len(feat_cols) - len(feat_cols_final)}

  Balancing method:    SMOTE (k=5 nearest neighbours)
  Scaling:             StandardScaler (zero mean, unit variance)

  Output files:
    {OUT_CSV:<40} ← inspect in Excel/pandas
    {OUT_X_NPY:<40} ← X  for transformer  shape={X_scaled.shape}
    {OUT_Y_NPY:<40} ← y  labels           shape={y_bal.shape}
    {OUT_FEATS:<40} ← feature names + F-scores
    {OUT_LABELS:<40} ← label→class mapping

  Transformer input:
    X = np.load('{OUT_X_NPY}')   # shape ({len(y_bal)}, {len(feat_cols_final)})
    y = np.load('{OUT_Y_NPY}')   # shape ({len(y_bal)},)
    # Reshape for sequence transformer:
    X_seq = X.reshape({len(y_bal)}, {len(feat_cols_final)}, 1)
{'='*65}
""")

=================================================================
ICMP COVERT CHANNEL — FEATURE SELECTION + BALANCING PIPELINE
=================================================================

[1] Loaded: 662 flows × 152 columns
    Class distribution:
      Header_Manipulation: 500
      Flow_Blending: 81
      Time_Obfuscation: 81

    Raw feature count: 148

[2] Dropping dead / null features ...
    Zero-variance: 14
    All-null:      2
    Dropped:       ['to_rtt_std', 'fb_orphan_rep_ratio', 'hm_ip_id_delta_mean', 'fb_ttl_consistency', 'fb_ttl_std', 'fb_truncation_ratio', 'fb_echo_rep_count', 'hm_ip_id_entropy', 'to_rtt_anomaly', 'hm_frag_nonzero_ratio', 'to_rtt_mean', 'hm_dscp_anomaly_ratio', 'to_rtt_entropy', 'hm_flag_anomaly_ratio']
    Remaining:     134

[3] Computing ANOVA F-scores (threshold = 5.0) ...
    Dropped (F < 5.0): 37
    Dropped features: ['fb_echo_req_count', 'fb_packet_count', 'fb_pkt_size_min', 'fb_pps', 'fb_req_reply_ratio', 'hm_seq_be_le_corr', 'hm_seq_jump_count', 'to_burst_count', 'to_burst_size_max', 'to_burst_size_mean', 'to_burst_size_std', 'to_clock_skew', 'to_fft_freq_0', 'to_fft_freq_1', 'to_fft_freq_2', 'to_fft_freq_3', 'to_fft_freq_4', 'to_fft_mag_0', 'to_fft_mag_1', 'to_fft_mag_2', 'to_fft_mag_3', 'to_fft_mag_4', 'to_ibi_entropy', 'to_ibi_mean', 'to_ibi_std', 'to_idle_count', 'to_idle_dur_max', 'to_idle_dur_mean', 'to_ipt_ac_10', 'to_ipt_ac_4', 'to_ipt_ac_5', 'to_ipt_ac_6', 'to_ipt_ac_7', 'to_ipt_ac_8', 'to_ipt_ac_9', 'to_ipt_kurt', 'to_jitter_entropy']
    Remaining:        97

[4] Applying covert-relevance filter ...
    Covert-relevant kept: 97
    Extra high-F added:   0
    Final feature count:  97

    Header Manipulation: 28 features
    Payload Bytes: 10 features
    Flow Blending: 41 features
    Time Obfuscation: 18 features

[5] Building clean feature matrix ...
    X shape: (662, 97)
    y shape: (662,)
    Any NaN: False

[6] Applying SMOTE to balance classes ...
    Class 1 (Flow_Blending): 81 real + 419 synthetic = 500
    Class 2 (Time_Obfuscation): 81 real + 419 synthetic = 500

    Balanced dataset: (1500, 97)
      Header_Manipulation: 500
      Flow_Blending: 500
      Time_Obfuscation: 500

[7] Standardising features (zero mean, unit variance) ...
    Global mean range:  [-0.3307, 74029.7734]
    Global std  range:  [0.000657, 84138.9844]
    Scaled X range:     [-7.9141, 24.7895]
    Any NaN after scale: False

[8] Saving outputs ...
    icmp_covert_balanced.csv: (1500, 99)
    icmp_covert_scaled.npy: (1500, 97)
    icmp_covert_labels.npy: (1500,)
    icmp_covert_feature_names.txt: 97 features listed
    icmp_covert_label_map.txt

=================================================================
PIPELINE COMPLETE — TRANSFORMER-READY DATASET
=================================================================

  Input flows:          662  (500 HM / 81 FB / 81 TO)
  Output flows:        1500  (500 per class × 3)
  Features:            97
    Header Manipulation: 28 (hm_*)
    Payload Bytes:       10 (pld_*)
    Flow Blending:       41 (fb_*)
    Time Obfuscation:    18 (to_*)

  Dropped features:
    Dead/zero-variance:  14
    Low F-score (<5.0):   37
    Not covert-relevant: 0

  Balancing method:    SMOTE (k=5 nearest neighbours)
  Scaling:             StandardScaler (zero mean, unit variance)

  Output files:
    icmp_covert_balanced.csv                 ← inspect in Excel/pandas
    icmp_covert_scaled.npy                   ← X  for transformer  shape=(1500, 97)
    icmp_covert_labels.npy                   ← y  labels           shape=(1500,)
    icmp_covert_feature_names.txt            ← feature names + F-scores
    icmp_covert_label_map.txt                ← label→class mapping

  Transformer input:
    X = np.load('icmp_covert_scaled.npy')   # shape (1500, 97)
    y = np.load('icmp_covert_labels.npy')   # shape (1500,)
    # Reshape for sequence transformer:
    X_seq = X.reshape(1500, 97, 1)
=================================================================

In [ ]:
# ╔══════════════════════════════════════════════════════════════════════════╗
# ║   ICMP COVERT CHANNEL — 1500 BALANCED FLOW EXTRACTOR                   ║
# ║   For Google Colab                                                      ║
# ║                                                                         ║
# ║   Input  : ICMP-PACKET1ST-FINAL.csv  (17,790 packets, 29 cols)         ║
# ║            ICMP-PACKETLEVEL2ND-FINAL.csv (100,056 packets, 29 cols)    ║
# ║   Output : icmp_1500_flows.csv  — 1500 flows × 67 features             ║
# ║            icmp_X.npy           — scaled feature matrix (1500, 67)     ║
# ║            icmp_y.npy           — labels (1500,)                       ║
# ║                                                                         ║
# ║   Classes: 0=Header_Manipulation  1=Flow_Blending  2=Time_Obfuscation  ║
# ║                                                                         ║
# ║   Window strategy (adaptive per class):                                 ║
# ║     TTL=64  (Header Manipulation): 5s window, 2.5s step → 500 flows   ║
# ║     TTL=128 (Flow Blending)      : 1s window, 0.4s step → 500 flows   ║
# ║     TTL=255 (Time Obfuscation)   : 1s window, 0.4s step → 500 flows   ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# ── CELL 1: Install dependencies ─────────────────────────────────────────────
# !pip install scipy -q   # usually pre-installed in Colab

# ── CELL 2: Imports ───────────────────────────────────────────────────────────
import re, warnings, itertools, zlib
import numpy as np
import pandas as pd
from scipy import stats
from scipy.fft import rfft
warnings.filterwarnings("ignore")

# ── CELL 3: CONFIG ────────────────────────────────────────────────────────────
# ↓↓↓  Update these paths to match your Google Drive or Colab upload location
FILE1 = "/content/ICMP-PACKET1ST-FINAL.csv"       # 17,790 packets (has raw payload + bad checksums)
FILE2 = "/content/ICMP-PACKETLEVEL2ND-FINAL.csv"  # 100,056 packets

OUTPUT_CSV   = "/content/icmp_1500_flows.csv"
OUTPUT_X_NPY = "/content/icmp_X.npy"
OUTPUT_Y_NPY = "/content/icmp_y.npy"

# Adaptive window per TTL class
TTL_WINDOW = {
    64:  (5.0, 2.5),   # (window_sec, step_sec) — 2938s capture → 1144+ windows
    128: (1.0, 0.4),   # 200s capture → 500 windows
    255: (1.0, 0.4),   # 200s capture → 500 windows
}
TTL_LABEL  = {64: 0, 128: 1, 255: 2}
LABEL_NAME = {0: "Header_Manipulation", 1: "Flow_Blending", 2: "Time_Obfuscation"}

TARGET_PER_CLASS = 500   # 500 × 3 = 1500 total
MIN_PKTS         = 3     # minimum packets per window
BURST_GAP        = 0.2   # seconds
IDLE_THR         = 1.0   # seconds
RANDOM_SEED      = 42
np.random.seed(RANDOM_SEED)

COVERT_IDS = {0xDEAD, 0xBEEF, 0xCAFE, 0xFACE, 0xFEED, 0x1337, 0x4141}

# ── CELL 4: PARSERS & HELPERS ─────────────────────────────────────────────────
RE_TTL  = re.compile(r'ttl=(\d+)',            re.I)
RE_ID   = re.compile(r'id=0x([0-9a-fA-F]+)')
RE_SEQ  = re.compile(r'seq=(\d+)/')
RE_TYPE = re.compile(r'Echo \(ping\) (request|reply)', re.I)

def parse_info(s):
    s  = str(s)
    mt = RE_TYPE.search(s); msg_type = mt.group(1).lower() if mt else 'other'
    mi = RE_ID.search(s);   icmp_id  = int(mi.group(1), 16) if mi else np.nan
    ms = RE_SEQ.search(s);  icmp_seq = int(ms.group(1))     if ms else np.nan
    mt = RE_TTL.search(s);  ttl      = int(mt.group(1))     if mt else np.nan
    return msg_type, icmp_id, icmp_seq, ttl

def entropy(vals):
    arr = np.asarray(vals, dtype=float)
    if len(arr) < 2 or arr.std() == 0: return 0.0
    bins = np.linspace(arr.min(), arr.max() + 1e-9, min(257, len(arr)+1))
    c, _ = np.histogram(arr, bins=bins)
    p = c / c.sum(); p = p[p > 0]
    return float(-np.sum(p * np.log2(p)))

def kl_div(sizes, mu=84, sd=30):
    arr = np.asarray(sizes, dtype=float)
    if len(arr) < 2: return 0.0
    bins = np.linspace(arr.min()-1, arr.max()+1, 33)
    p, _ = np.histogram(arr, bins=bins, density=True)
    q = stats.norm.pdf((bins[:-1]+bins[1:])/2, mu, sd)
    p += 1e-10; q += 1e-10; p /= p.sum(); q /= q.sum()
    return float(np.sum(p * np.log(p/q)))

def periodicity(ipt):
    if len(ipt) < 8: return 0.0
    arr  = np.asarray(ipt, dtype=float) - np.mean(ipt)
    spec = np.abs(rfft(arr)) ** 2
    return float(spec[1:].max() / spec[1:].sum()) if spec[1:].sum() > 0 else 0.0

def payload_entropy(hex_series):
    """Mean byte entropy + compression ratio across flow packets."""
    ents, ratios, prints, nulls, bigrams = [], [], [], [], []
    for h in hex_series.dropna():
        h = str(h).replace(':', '').replace(' ', '').strip()
        if not h: continue
        try:    raw = bytes.fromhex(h)
        except: continue
        if not raw: continue
        arr = np.frombuffer(raw, dtype=np.uint8)
        cnt = np.bincount(arr, minlength=256)
        p   = cnt/cnt.sum(); pnz = p[p>0]
        ents.append(float(-np.sum(pnz*np.log2(pnz))))
        try:    ratios.append(len(zlib.compress(raw,9))/len(raw))
        except: pass
        prints.append(sum(32<=b<=126 for b in arr)/len(arr))
        nulls.append(float(np.sum(arr==0)/len(arr)))
        if len(arr)>=2:
            bg = arr[:-1].astype(int)*256+arr[1:].astype(int)
            bc = np.bincount(bg,minlength=65536)/len(bg); bcnz=bc[bc>0]
            bigrams.append(float(-np.sum(bcnz*np.log2(bcnz))))
    def m(lst): return float(np.mean(lst)) if lst else np.nan
    return m(ents), m(ratios), m(prints), m(nulls), m(bigrams)

# ── CELL 5: FEATURE EXTRACTOR ─────────────────────────────────────────────────
def extract_features(grp, has_payload=False, has_checksum=False):
    """
    Extract 67 flow-level features from a packet window.
    All feature names match standard network/ICMP terminology.
    """
    grp   = grp.sort_values('time').reset_index(drop=True)
    n     = len(grp)
    if n < MIN_PKTS: return None

    times = grp['time'].values.astype(float)
    lens  = grp['length'].values.astype(float)
    pld   = (lens - 42).clip(0)
    ttls  = grp['ttl'].dropna().values.astype(float)
    seqs  = grp['icmp_seq'].dropna().values.astype(float)
    ids   = grp['icmp_id'].dropna().values.astype(float)
    ipt   = np.diff(times) if n > 1 else np.array([0.0])
    req   = grp[grp['msg_type'] == 'request']
    rep   = grp[grp['msg_type'] == 'reply']

    f = {}

    # ══════════════════════════════════════════════════════════════════
    # GROUP A — HEADER MANIPULATION (30 features)
    # Detect abuse of ICMP header fields to hide/encode data
    # ══════════════════════════════════════════════════════════════════

    # --- Type & Code field abuse ---
    tc  = grp['msg_type'].value_counts()
    tp  = (tc / tc.sum()).values
    f['icmp_type_code_entropy']       = float(-np.sum(tp * np.log2(tp + 1e-10)))
    f['icmp_invalid_type_ratio']      = float(tc.get('other', 0) / n)
    f['icmp_non_echo_ratio']          = float((grp['msg_type'] != 'request').sum() / n)

    if 'icmp_type_raw' in grp.columns:
        tvc   = grp['icmp_type_raw'].value_counts()
        tprob = (tvc / tvc.sum()).values
        f['icmp_type_diversity']      = float(-np.sum(tprob * np.log2(tprob + 1e-10)))
        f['icmp_nonstandard_type_count'] = int(
            (~grp['icmp_type_raw'].str.contains('Echo', na=False)).sum())
    else:
        f['icmp_type_diversity']      = f['icmp_type_code_entropy']
        f['icmp_nonstandard_type_count'] = int(tc.get('other', 0))

    if 'icmp_code' in grp.columns:
        codes = pd.to_numeric(grp['icmp_code'], errors='coerce').dropna()
        f['icmp_code_entropy']        = entropy(codes)
        f['icmp_nonzero_code_ratio']  = float((codes != 0).sum() / max(len(codes), 1))
    else:
        f['icmp_code_entropy']        = 0.0
        f['icmp_nonzero_code_ratio']  = 0.0

    # --- Checksum manipulation ---
    if has_checksum and 'chk_status' in grp.columns:
        f['icmp_bad_checksum_ratio']  = float((grp['chk_status'] == 'Bad').sum() / n)
    else:
        f['icmp_bad_checksum_ratio']  = 0.0

    if 'checksum_hex' in grp.columns:
        chk = grp['checksum_hex'].dropna().apply(
            lambda x: int(str(x).replace('0x',''), 16) if str(x).startswith('0x') else 0)
        f['icmp_checksum_entropy']    = entropy(chk)
        f['icmp_checksum_delta_mean'] = float(np.mean(np.abs(np.diff(chk.values.astype(float))))) \
                                        if len(chk) > 1 else 0.0
    else:
        f['icmp_checksum_entropy']    = 0.0
        f['icmp_checksum_delta_mean'] = 0.0

    # --- IP Identification field ---
    if 'ip_id' in grp.columns:
        ip_ids = grp['ip_id'].dropna().apply(
            lambda x: int(str(x).replace('0x',''), 16) if str(x).startswith('0x') else 0)
        f['ip_id_reuse_rate']         = float(1 - len(np.unique(ip_ids)) / max(len(ip_ids), 1))
    else:
        f['ip_id_reuse_rate']         = 0.0

    # --- ICMP Identifier field anomalies ---
    if len(ids) > 1:
        f['icmp_id_reuse_rate']       = float(1 - len(np.unique(ids)) / len(ids))
        f['icmp_id_entropy']          = entropy(ids)
        id_d = np.diff(ids)
        f['icmp_id_delta_mean']       = float(np.mean(np.abs(id_d)))
        f['icmp_id_delta_std']        = float(np.std(id_d))
        ml = min(len(ids), len(seqs))
        if ml > 2:
            try:
                c = np.corrcoef(ids[:ml], seqs[:ml])[0, 1]
                f['icmp_id_seq_correlation'] = float(c) if not np.isnan(c) else 0.0
            except: f['icmp_id_seq_correlation'] = 0.0
        else: f['icmp_id_seq_correlation'] = 0.0
    else:
        f['icmp_id_reuse_rate']       = 0.0
        f['icmp_id_entropy']          = 0.0
        f['icmp_id_delta_mean']       = 0.0
        f['icmp_id_delta_std']        = 0.0
        f['icmp_id_seq_correlation']  = 0.0

    f['icmp_covert_id_count']         = int(grp['icmp_id'].apply(
        lambda x: 1 if (pd.notna(x) and int(x) in COVERT_IDS) else 0).sum())

    # --- Sequence number irregularities ---
    if len(seqs) > 1:
        sd = np.diff(seqs)
        f['icmp_seq_increment_std']   = float(np.std(sd))
        f['icmp_seq_entropy']         = entropy(seqs)
        f['icmp_seq_monotone_ratio']  = float(np.sum(sd > 0) / len(sd))
        f['icmp_seq_autocorr_lag1']   = float(np.corrcoef(seqs[:-1], seqs[1:])[0,1]) \
                                        if len(seqs) > 2 else 0.0
    else:
        f['icmp_seq_increment_std']   = 0.0
        f['icmp_seq_entropy']         = 0.0
        f['icmp_seq_monotone_ratio']  = 0.0
        f['icmp_seq_autocorr_lag1']   = 0.0

    # --- Payload length anomalies ---
    f['icmp_payload_len_mean']        = float(np.mean(pld))
    f['icmp_payload_len_std']         = float(np.std(pld))
    f['icmp_payload_len_entropy']     = entropy(pld)
    mode_p = float(stats.mode(pld, keepdims=True).mode[0])
    f['icmp_nonstd_payload_ratio']    = float(np.sum(pld != mode_p) / n)

    # --- Raw payload byte analysis (data hidden inside payload) ---
    if has_payload and 'payload_hex' in grp.columns:
        ent, comp, prnt, null, bigr = payload_entropy(grp['payload_hex'])
    else:
        ent, comp, prnt, null, bigr = np.nan, np.nan, np.nan, np.nan, np.nan
    f['payload_byte_entropy']         = ent
    f['payload_compression_ratio']    = comp
    f['payload_printable_ratio']      = prnt
    f['payload_null_byte_ratio']      = null
    f['payload_bigram_entropy']       = bigr

    # ══════════════════════════════════════════════════════════════════
    # GROUP B — FLOW BLENDING (24 features)
    # Detect traffic mimicking legitimate ICMP to blend in
    # ══════════════════════════════════════════════════════════════════

    f['flow_ttl_mean']                = float(np.mean(ttls)) if len(ttls) > 0 else np.nan
    f['flow_pkt_size_mean']           = float(np.mean(lens))
    f['flow_pkt_size_std']            = float(np.std(lens))
    f['flow_pkt_size_max']            = float(np.max(lens))
    f['flow_pkt_size_median']         = float(np.median(lens))
    f['flow_pkt_size_entropy']        = entropy(lens)
    f['flow_pkt_size_skewness']       = float(stats.skew(lens))     if n > 2 else 0.0
    f['flow_pkt_size_kurtosis']       = float(stats.kurtosis(lens)) if n > 2 else 0.0
    f['flow_pkt_size_cv']             = float(np.std(lens)/np.mean(lens)) \
                                        if np.mean(lens) > 0 else 0.0
    f['flow_pkt_size_iqr']            = float(np.percentile(lens,75)-np.percentile(lens,25))

    # Packet size histogram (8 bins across 60–1442 bytes)
    bin_edges = np.linspace(60, 1442, 9)
    hist, _   = np.histogram(lens, bins=bin_edges)
    for i, h in enumerate(hist):
        f[f'flow_size_bin_{i}']       = float(h / n)   # bins 0–7

    # Size transition matrix (4×4) — consecutive packet size patterns
    bin_idx = np.digitize(lens, np.linspace(60, 1442, 5)).clip(1, 4) - 1
    for i in range(4):
        for j in range(4):
            f[f'flow_size_trans_{i}{j}'] = float(
                ((bin_idx[:-1]==i)&(bin_idx[1:]==j)).sum() / max(n-1, 1))

    # Baseline deviation
    f['flow_kl_divergence']           = kl_div(lens)
    mode_l = float(stats.mode(lens, keepdims=True).mode[0])
    f['flow_uniform_size_ratio']      = float(np.sum(lens == mode_l) / n)

    # Request/reply asymmetry
    f['flow_orphan_req_ratio']        = float(len(req) / n)
    req_bytes = float(req['length'].sum()) if len(req) else 0.0
    rep_bytes = float(rep['length'].sum()) if len(rep) else 0.0
    f['flow_byte_asymmetry']          = req_bytes / max(rep_bytes, 1.0)
    dur = float(times[-1]-times[0]) if n > 1 else 0.0
    f['flow_bytes_per_sec']           = float(lens.sum()) / dur if dur > 0 else 0.0

    # ══════════════════════════════════════════════════════════════════
    # GROUP C — TIME OBFUSCATION (13 features)
    # Detect timing manipulation to encode data or evade detection
    # ══════════════════════════════════════════════════════════════════

    f['ipt_mean']                     = float(np.mean(ipt))
    f['ipt_std']                      = float(np.std(ipt))
    f['ipt_median']                   = float(np.median(ipt))
    f['ipt_q90']                      = float(np.percentile(ipt, 90))
    f['ipt_coeff_variation']          = float(np.std(ipt)/np.mean(ipt)) \
                                        if np.mean(ipt) > 0 else 0.0
    f['ipt_iqr']                      = float(np.percentile(ipt,75)-np.percentile(ipt,25))
    f['ipt_entropy']                  = entropy(ipt)
    f['ipt_skewness']                 = float(stats.skew(ipt))  if len(ipt) > 2 else 0.0

    # Autocorrelation (timing pattern detection)
    for lag in [1, 2]:
        if len(ipt) > lag + 1:
            try:
                ac = np.corrcoef(ipt[:-lag], ipt[lag:])[0, 1]
                f[f'ipt_autocorr_lag{lag}']  = float(ac) if not np.isnan(ac) else 0.0
            except: f[f'ipt_autocorr_lag{lag}'] = 0.0
        else: f[f'ipt_autocorr_lag{lag}'] = 0.0

    f['ipt_periodicity_score']        = periodicity(ipt)
    f['ipt_timing_regularity']        = f['ipt_autocorr_lag1']
    jit = np.abs(ipt - np.mean(ipt))
    f['ipt_jitter_mean']              = float(np.mean(jit))

    return f

# ── CELL 6: LOAD & STANDARDISE FILES ─────────────────────────────────────────
def load_file(path, encoding='latin1'):
    print(f"  Loading {path} ...")
    df = pd.read_csv(path, encoding=encoding)
    df.columns = [c.strip().strip('"') for c in df.columns]

    rename = {
        'No.':'pkt_no','Time':'time','Source':'src','Destination':'dst',
        'Length':'length','Info':'info',
        'Checksum':'checksum_hex','Checksum Status':'chk_status',
        'Identifier (BE)':'icmp_id_be','Sequence Number (BE)':'seq_be',
        'Sequence Number (LE)':'icmp_seq_le',
        'Identification':'ip_id','Flags':'ip_flags',
        'Fragment Offset':'frag_offset',
        'Differentiated Services Codepoint':'dscp',
        'Type.1':'icmp_type_raw','Code':'icmp_code',
        'Data':'payload_hex','Frame Length':'frame_len',
        'Capture Length':'cap_len',
    }
    df = df.rename(columns={k:v for k,v in rename.items() if k in df.columns})
    df['time']   = pd.to_numeric(df['time'],   errors='coerce')
    df['length'] = pd.to_numeric(df['length'], errors='coerce')
    df = df.dropna(subset=['time','length']).reset_index(drop=True)

    parsed        = df['info'].apply(parse_info)
    df['msg_type']= [p[0] for p in parsed]
    df['icmp_id'] = pd.array([p[1] for p in parsed], dtype='Float64')
    df['icmp_seq']= pd.array([p[2] for p in parsed], dtype='Float64')
    df['ttl']     = pd.array([p[3] for p in parsed], dtype='Float64')

    if 'icmp_id_be' in df.columns:
        df['icmp_id'] = df['icmp_id'].fillna(df['icmp_id_be'])
    if 'seq_be' in df.columns:
        df['icmp_seq'] = df['icmp_seq'].fillna(df['seq_be'])
    if 'icmp_type_raw' in df.columns:
        df.loc[~df['icmp_type_raw'].str.contains('Echo',case=False,na=False),'msg_type'] = 'other'

    ttl_dist = df['ttl'].value_counts().to_dict()
    print(f"    {len(df):,} packets | TTL dist: { {int(k):v for k,v in ttl_dist.items() if pd.notna(k)} }")
    return df

print("="*65)
print("ICMP COVERT CHANNEL — 1500 FLOW EXTRACTOR")
print("="*65)

print("\n[1] Loading packet files ...")
df1 = load_file(FILE1)
df2 = load_file(FILE2)

# Mark which file has raw payload bytes
df1['_has_payload']  = True;  df1['_has_checksum'] = True
df2['_has_payload']  = False; df2['_has_checksum'] = True

df_all = pd.concat([df1, df2], ignore_index=True)
df_all['ttl_int'] = df_all['ttl'].dropna().astype(int)
df_all = df_all[df_all['ttl_int'].isin(TTL_LABEL)].reset_index(drop=True)
print(f"\n[2] Combined: {len(df_all):,} packets")
print(f"    TTL distribution: { df_all['ttl_int'].value_counts().to_dict() }")

# ── CELL 7: SLIDING WINDOW EXTRACTION ────────────────────────────────────────
print(f"\n[3] Extracting flow windows ...")

records = []

for ttl_val, label in TTL_LABEL.items():
    WINDOW_SEC, STEP_SEC = TTL_WINDOW[ttl_val]
    sub = df_all[df_all['ttl_int'] == ttl_val].sort_values('time').reset_index(drop=True)
    if len(sub) == 0: continue

    t0, t1    = sub['time'].min(), sub['time'].max()
    win_count = 0

    for ws in np.arange(t0, t1 - WINDOW_SEC + 0.001, STEP_SEC):
        we     = ws + WINDOW_SEC
        window = sub[(sub['time'] >= ws) & (sub['time'] < we)].copy()
        if len(window) < MIN_PKTS: continue

        has_pld = bool(window['_has_payload'].any())
        has_chk = bool(window['_has_checksum'].any())
        feats   = extract_features(window, has_payload=has_pld, has_checksum=has_chk)
        if feats is None: continue

        feats['label']      = label
        feats['label_name'] = LABEL_NAME[label]
        records.append(feats)
        win_count += 1

    print(f"    TTL={ttl_val} ({LABEL_NAME[label]:25s}): {win_count:,} windows "
          f"[{WINDOW_SEC}s/{STEP_SEC}s step]")

df_flows = pd.DataFrame(records)
print(f"\n    Total before balancing: {len(df_flows):,}")
print(f"    {df_flows['label_name'].value_counts().to_string()}")

# ── CELL 8: BALANCE TO 500 PER CLASS ─────────────────────────────────────────
print(f"\n[4] Balancing to {TARGET_PER_CLASS} per class ...")

rng = np.random.default_rng(RANDOM_SEED)

# Feature columns only
feat_cols = [c for c in df_flows.columns if c not in ('label','label_name')]

balanced = []
for cls in sorted(LABEL_NAME.keys()):
    cls_df = df_flows[df_flows['label'] == cls].copy()
    n = len(cls_df)
    if n == 0:
        print(f"  WARNING: no flows for class {cls} ({LABEL_NAME[cls]})")
        continue
    if n >= TARGET_PER_CLASS:
        sampled = cls_df.sample(n=TARGET_PER_CLASS, random_state=RANDOM_SEED)
        print(f"  {LABEL_NAME[cls]:25s}: {n:,} → {TARGET_PER_CLASS} (random sample)")
        balanced.append(sampled)
    else:
        # SMOTE: synthetic oversampling
        X_cls = cls_df[feat_cols].copy()
        # Fill NaN before SMOTE
        for col in X_cls.columns:
            if X_cls[col].isna().any():
                med = X_cls[col].median()
                X_cls[col] = X_cls[col].fillna(med if not np.isnan(med) else 0.0)
        X_arr = X_cls.values.astype(np.float32)
        n_need = TARGET_PER_CLASS - n
        k      = min(5, n - 1)
        synth  = []
        for _ in range(n_need):
            i        = rng.integers(0, n)
            sample   = X_arr[i]
            dists    = np.sum((X_arr - sample)**2, axis=1)
            dists[i] = np.inf
            nn_idx   = np.argpartition(dists, k)[:k]
            neighbour= X_arr[rng.choice(nn_idx)]
            alpha    = rng.random()
            synth.append(sample + alpha*(neighbour - sample))
        synth_df = pd.DataFrame(np.array(synth, dtype=np.float32), columns=feat_cols)
        synth_df['label']      = cls
        synth_df['label_name'] = LABEL_NAME[cls]
        combined = pd.concat([cls_df, synth_df], ignore_index=True)
        print(f"  {LABEL_NAME[cls]:25s}: {n} real + {n_need} SMOTE synthetic = {TARGET_PER_CLASS}")
        balanced.append(combined)

df_bal = pd.concat(balanced, ignore_index=True).sample(
    frac=1, random_state=RANDOM_SEED).reset_index(drop=True)

print(f"\n  Final: {len(df_bal):,} flows")
print(f"  {df_bal['label_name'].value_counts().to_string()}")

# ── CELL 9: CLEAN & SELECT RELEVANT FEATURES ─────────────────────────────────
print("\n[5] Selecting relevant features ...")

# The 67 covert-relevant features with proper names
SELECTED_FEATURES = [
    # ── HEADER MANIPULATION (30) ──────────────────────────────────────
    'icmp_type_code_entropy',       # entropy of type-code combinations
    'icmp_invalid_type_ratio',      # fraction non-standard ICMP types
    'icmp_non_echo_ratio',          # fraction not echo request/reply
    'icmp_type_diversity',          # diversity of ICMP type strings
    'icmp_nonstandard_type_count',  # count of non-echo type packets
    'icmp_code_entropy',            # entropy of ICMP code field
    'icmp_nonzero_code_ratio',      # non-zero codes = header field abuse
    'icmp_bad_checksum_ratio',      # bad checksums = direct manipulation
    'icmp_checksum_entropy',        # randomness of checksum values
    'icmp_checksum_delta_mean',     # mean delta between consecutive checksums
    'ip_id_reuse_rate',             # IP identification field reuse rate
    'icmp_id_reuse_rate',           # ICMP identifier field reuse rate
    'icmp_id_entropy',              # entropy of ICMP identifier values
    'icmp_id_delta_mean',           # mean step between ICMP identifiers
    'icmp_id_delta_std',            # variability of ICMP identifier steps
    'icmp_id_seq_correlation',      # ID-sequence correlation (tool fingerprint)
    'icmp_covert_id_count',         # known covert identifiers (0xDEAD etc.)
    'icmp_seq_increment_std',       # std of sequence number increments
    'icmp_seq_entropy',             # entropy of sequence numbers
    'icmp_seq_monotone_ratio',      # fraction of monotone seq increments
    'icmp_seq_autocorr_lag1',       # autocorrelation of sequence series
    'icmp_payload_len_mean',        # mean payload length
    'icmp_payload_len_std',         # std of payload lengths
    'icmp_payload_len_entropy',     # entropy of payload length distribution
    'icmp_nonstd_payload_ratio',    # fraction with non-standard payload size
    'payload_byte_entropy',         # mean byte entropy (detects hidden data)
    'payload_compression_ratio',    # low ratio = random/encrypted content
    'payload_printable_ratio',      # high = text-based covert channel
    'payload_null_byte_ratio',      # null byte stuffing patterns
    'payload_bigram_entropy',       # byte-pair transition patterns
    # ── FLOW BLENDING (24) ────────────────────────────────────────────
    'flow_ttl_mean',                # TTL value (tool fingerprint)
    'flow_pkt_size_mean',           # mean packet size
    'flow_pkt_size_std',            # packet size variability
    'flow_pkt_size_max',            # maximum packet size
    'flow_pkt_size_median',         # median packet size
    'flow_pkt_size_entropy',        # entropy of size distribution
    'flow_pkt_size_skewness',       # skewness of size distribution
    'flow_pkt_size_kurtosis',       # kurtosis of size distribution
    'flow_pkt_size_cv',             # coefficient of variation of sizes
    'flow_pkt_size_iqr',            # interquartile range of sizes
    'flow_size_bin_0',              # fraction small packets (60-240B)
    'flow_size_bin_3',              # fraction medium-large (600-780B)
    'flow_size_bin_4',              # fraction large (780-960B)
    'flow_size_bin_6',              # fraction very large (1140-1320B)
    'flow_size_bin_7',              # fraction max-size (1320-1442B)
    'flow_size_trans_00',           # size transition: small → small
    'flow_size_trans_03',           # size transition: small → large
    'flow_size_trans_30',           # size transition: large → small
    'flow_size_trans_33',           # size transition: large → large
    'flow_kl_divergence',           # KL divergence from normal ICMP baseline
    'flow_uniform_size_ratio',      # fraction with uniform/fixed size
    'flow_orphan_req_ratio',        # requests without replies (covert=100%)
    'flow_byte_asymmetry',          # req/reply byte volume asymmetry
    'flow_bytes_per_sec',           # bytes per second (rate mimicry)
    # ── TIME OBFUSCATION (13) ─────────────────────────────────────────
    'ipt_mean',                     # mean inter-packet time
    'ipt_std',                      # std of inter-packet times
    'ipt_median',                   # median inter-packet time
    'ipt_q90',                      # 90th percentile inter-packet time
    'ipt_coeff_variation',          # coefficient of variation (timing regularity)
    'ipt_iqr',                      # IQR of inter-packet times
    'ipt_entropy',                  # entropy of timing distribution
    'ipt_skewness',                 # skewness of timing distribution
    'ipt_autocorr_lag1',            # lag-1 autocorrelation (timing pattern)
    'ipt_autocorr_lag2',            # lag-2 autocorrelation (timing pattern)
    'ipt_periodicity_score',        # FFT-based periodicity score
    'ipt_timing_regularity',        # overall timing regularity index
    'ipt_jitter_mean',              # mean absolute jitter
]

# Keep only features present in dataframe
avail = [f for f in SELECTED_FEATURES if f in df_bal.columns]
missing = [f for f in SELECTED_FEATURES if f not in df_bal.columns]
if missing:
    print(f"  Missing (will skip): {missing}")
print(f"  Selected: {len(avail)} features")

X_df = df_bal[avail].copy()

# Fill NaN (payload features are NaN for flows without raw bytes)
for col in X_df.columns:
    if X_df[col].isna().any():
        med = X_df[col].median()
        X_df[col] = X_df[col].fillna(med if not np.isnan(med) else 0.0)

X = X_df.values.astype(np.float32)
y = df_bal['label'].values.astype(int)
print(f"  X shape: {X.shape},  y shape: {y.shape},  NaN: {np.isnan(X).any()}")

# ── CELL 10: STANDARDISE ──────────────────────────────────────────────────────
print("\n[6] StandardScaler ...")
mean = X.mean(axis=0);  std = X.std(axis=0);  std[std==0] = 1.0
X_sc = ((X - mean) / std).astype(np.float32)
print(f"  Scaled range: [{X_sc.min():.3f}, {X_sc.max():.3f}]")
print(f"  NaN: {np.isnan(X_sc).any()}")

# ── CELL 11: SAVE ─────────────────────────────────────────────────────────────
print("\n[7] Saving ...")

# Readable CSV
out_df = X_df.copy()
out_df['label']      = y
out_df['label_name'] = [LABEL_NAME[l] for l in y]
out_df.to_csv(OUTPUT_CSV, index=False)
print(f"  {OUTPUT_CSV}:  {out_df.shape}")

# Numpy arrays for transformer training
np.save(OUTPUT_X_NPY, X_sc)
np.save(OUTPUT_Y_NPY, y)
print(f"  {OUTPUT_X_NPY}: {X_sc.shape}")
print(f"  {OUTPUT_Y_NPY}: {y.shape}")

# ── CELL 12: SUMMARY ──────────────────────────────────────────────────────────
print(f"""
{'='*65}
✓  DONE — TRANSFORMER-READY DATASET
{'='*65}
  Total flows  : {len(y):,}   (perfectly balanced)
  Per class    : {TARGET_PER_CLASS}
  Features     : {len(avail)}
                 ├─ Header Manipulation : 30  (icmp_* + payload_*)
                 ├─ Flow Blending       : 24  (flow_*)
                 └─ Time Obfuscation    : 13  (ipt_*)
  Classes:
    0 = Header_Manipulation   ({(y==0).sum()} flows)
    1 = Flow_Blending         ({(y==1).sum()} flows)
    2 = Time_Obfuscation      ({(y==2).sum()} flows)

  Load for transformer:
    X = np.load('{OUTPUT_X_NPY}')  # shape ({len(y)}, {len(avail)})
    y = np.load('{OUTPUT_Y_NPY}')  # shape ({len(y)},)

  Reshape as sequence (feature = 1 token each):
    X_seq = X.reshape({len(y)}, {len(avail)}, 1)
{'='*65}
""")

In [ ]:
output = pd.read_csv("/content/icmp_covert_balanced.csv")

In [ ]:
output.head()

,hm_type_code_entropy,hm_invalid_type_ratio,hm_non_echo_ratio,hm_icmp_type_diversity,hm_nonstandard_type_count,hm_code_entropy,hm_nonzero_code_ratio,hm_bad_checksum_ratio,hm_good_checksum_ratio,hm_checksum_entropy,...,to_ipt_iqr,to_ipt_ac_1,to_ipt_ac_2,to_ipt_ac_3,to_periodic_score,to_timing_regularity,to_jitter_mean,to_jitter_std,label,label_name
0,0.710479,0.195062,0.195062,1.201882,61.293680,0.127871,0.013545,0.0,1.0,7.301762,...,0.016654,0.028034,0.087223,-0.019080,0.031932,0.028034,0.011458,0.010736,1,Flow_Blending
1,0.620539,0.154429,0.154429,0.995621,47.765520,0.138844,0.015038,0.0,1.0,7.316706,...,0.017260,0.086403,0.003745,0.004056,0.030711,0.086403,0.011151,0.009902,1,Flow_Blending
2,0.523929,0.118491,0.118491,0.818151,48.636395,0.161278,0.019111,0.0,1.0,6.704887,...,0.014242,0.000982,0.023488,0.025581,0.035381,0.000982,0.008518,0.006996,2,Time_Obfuscation
3,0.616137,0.152989,0.152989,1.000266,46.161842,0.219227,0.026187,0.0,1.0,7.347437,...,0.018184,0.036234,0.058503,-0.030084,0.052355,0.036234,0.012169,0.010467,1,Flow_Blending
4,0.496748,0.108958,0.108958,0.763977,46.476135,0.080167,0.008361,0.0,1.0,6.803574,...,0.011758,-0.034569,-0.004802,0.036720,0.022645,-0.034569,0.007775,0.007451,2,Time_Obfuscation

In [ ]:
output.shape

(1500, 99)

In [ ]:
output.columns.to_list()

['hm_type_code_entropy',
 'hm_invalid_type_ratio',
 'hm_non_echo_ratio',
 'hm_icmp_type_diversity',
 'hm_nonstandard_type_count',
 'hm_code_entropy',
 'hm_nonzero_code_ratio',
 'hm_bad_checksum_ratio',
 'hm_good_checksum_ratio',
 'hm_checksum_entropy',
 'hm_checksum_delta_mean',
 'hm_checksum_delta_std',
 'hm_ip_id_reuse_rate',
 'hm_seq_increment_std',
 'hm_seq_entropy',
 'hm_seq_monotone_ratio',
 'hm_seq_autocorr_lag1',
 'hm_id_reuse_rate',
 'hm_id_entropy',
 'hm_id_delta_mean',
 'hm_id_delta_std',
 'hm_id_seq_corr',
 'hm_covert_id_count',
 'hm_payload_len_mean',
 'hm_payload_len_std',
 'hm_payload_len_entropy',
 'hm_payload_len_variance',
 'hm_non_std_payload_ratio',
 'pld_byte_entropy_mean',
 'pld_byte_entropy_std',
 'pld_compress_ratio_mean',
 'pld_compress_ratio_std',
 'pld_printable_ratio_mean',
 'pld_printable_ratio_std',
 'pld_null_ratio_mean',
 'pld_null_ratio_std',
 'pld_bigram_entropy_mean',
 'pld_bigram_entropy_std',
 'fb_byte_count',
 'fb_flow_duration',
 'fb_bps',
 'fb_orphan_req_ratio',
 'fb_byte_asymmetry',
 'fb_ttl_mean',
 'fb_pkt_size_mean',
 'fb_pkt_size_std',
 'fb_pkt_size_max',
 'fb_pkt_size_median',
 'fb_pkt_size_entropy',
 'fb_pkt_size_skew',
 'fb_pkt_size_kurt',
 'fb_pkt_size_cv',
 'fb_pkt_size_iqr',
 'fb_size_bin_0',
 'fb_size_bin_1',
 'fb_size_bin_2',
 'fb_size_bin_3',
 'fb_size_bin_4',
 'fb_size_bin_5',
 'fb_size_bin_6',
 'fb_size_bin_7',
 'fb_size_trans_00',
 'fb_size_trans_01',
 'fb_size_trans_02',
 'fb_size_trans_03',
 'fb_size_trans_10',
 'fb_size_trans_11',
 'fb_size_trans_12',
 'fb_size_trans_13',
 'fb_size_trans_20',
 'fb_size_trans_21',
 'fb_size_trans_22',
 'fb_size_trans_23',
 'fb_size_trans_30',
 'fb_size_trans_31',
 'fb_size_trans_32',
 'fb_size_trans_33',
 'fb_uniform_size_ratio',
 'fb_kl_div_baseline',
 'to_ipt_mean',
 'to_ipt_std',
 'to_ipt_min',
 'to_ipt_max',
 'to_ipt_median',
 'to_ipt_q90',
 'to_ipt_q99',
 'to_ipt_entropy',
 'to_ipt_skew',
 'to_ipt_cv',
 'to_ipt_iqr',
 'to_ipt_ac_1',
 'to_ipt_ac_2',
 'to_ipt_ac_3',
 'to_periodic_score',
 'to_timing_regularity',
 'to_jitter_mean',
 'to_jitter_std',
 'label',
 'label_name']

In [ ]:
"""
ICMP Covert Channel — Feature Renaming to Standard Network Terminology
=======================================================================
Renames all 97 features to proper icmp_/ip_/flow_/ipt_ network names.
Removes old label columns, adds label_technique, label_binary, label_protocol.

Input : icmp_covert_balanced.csv
Output: icmp_model_ready.csv

Run in Google Colab.
"""

import pandas as pd
import numpy as np

# ── CONFIG ────────────────────────────────────────────────────────────────────
INPUT_FILE  = "/content/icmp_covert_balanced.csv"
OUTPUT_FILE = "/content/icmp_model_ready.csv"

TECHNIQUE_MAP = {
    0: 1,   # Header_Manipulation → 1
    2: 2,   # Time_Obfuscation    → 2
    1: 3,   # Flow_Blending       → 3
}
TECHNIQUE_NAME = {1: "Header_Manipulation", 2: "Time_Obfuscation", 3: "Flow_Blending"}

# ── COMPLETE RENAME MAP (old → new) ──────────────────────────────────────────
# Every feature renamed to standard ICMP/network terminology
# No technique prefix — names describe what is measured, not which class

RENAME_MAP = {

    # ── HEADER MANIPULATION FEATURES ─────────────────────────────────────────
    "hm_type_code_entropy"      : "icmp_type_code_entropy",
    "hm_invalid_type_ratio"     : "icmp_invalid_type_ratio",
    "hm_non_echo_ratio"         : "icmp_non_echo_ratio",
    "hm_icmp_type_diversity"    : "icmp_type_diversity",
    "hm_nonstandard_type_count" : "icmp_nonstandard_type_count",
    "hm_code_entropy"           : "icmp_code_field_entropy",
    "hm_nonzero_code_ratio"     : "icmp_nonzero_code_ratio",
    "hm_bad_checksum_ratio"     : "icmp_bad_checksum_ratio",
    "hm_good_checksum_ratio"    : "icmp_good_checksum_ratio",
    "hm_checksum_entropy"       : "icmp_checksum_entropy",
    "hm_checksum_delta_mean"    : "icmp_checksum_delta_mean",
    "hm_checksum_delta_std"     : "icmp_checksum_delta_std",
    "hm_ip_id_reuse_rate"       : "ip_id_reuse_rate",
    "hm_seq_increment_std"      : "icmp_seq_increment_std",
    "hm_seq_entropy"            : "icmp_seq_entropy",
    "hm_seq_monotone_ratio"     : "icmp_seq_monotone_ratio",
    "hm_seq_autocorr_lag1"      : "icmp_seq_autocorr_lag1",
    "hm_id_reuse_rate"          : "icmp_id_reuse_rate",
    "hm_id_entropy"             : "icmp_id_entropy",
    "hm_id_delta_mean"          : "icmp_id_delta_mean",
    "hm_id_delta_std"           : "icmp_id_delta_std",
    "hm_id_seq_corr"            : "icmp_id_seq_correlation",
    "hm_covert_id_count"        : "icmp_covert_id_count",
    "hm_payload_len_mean"       : "icmp_payload_len_mean",
    "hm_payload_len_std"        : "icmp_payload_len_std",
    "hm_payload_len_entropy"    : "icmp_payload_len_entropy",
    "hm_payload_len_variance"   : "icmp_payload_len_variance",
    "hm_non_std_payload_ratio"  : "icmp_nonstd_payload_ratio",

    # ── PAYLOAD BYTE FEATURES ────────────────────────────────────────────────
    "pld_byte_entropy_mean"     : "payload_byte_entropy_mean",
    "pld_byte_entropy_std"      : "payload_byte_entropy_std",
    "pld_compress_ratio_mean"   : "payload_compress_ratio_mean",
    "pld_compress_ratio_std"    : "payload_compress_ratio_std",
    "pld_printable_ratio_mean"  : "payload_printable_ratio_mean",
    "pld_printable_ratio_std"   : "payload_printable_ratio_std",
    "pld_null_ratio_mean"       : "payload_null_byte_ratio_mean",
    "pld_null_ratio_std"        : "payload_null_byte_ratio_std",
    "pld_bigram_entropy_mean"   : "payload_bigram_entropy_mean",
    "pld_bigram_entropy_std"    : "payload_bigram_entropy_std",

    # ── FLOW BLENDING FEATURES ───────────────────────────────────────────────
    "fb_byte_count"             : "flow_total_bytes",
    "fb_flow_duration"          : "flow_duration_sec",
    "fb_bps"                    : "flow_bytes_per_sec",
    "fb_orphan_req_ratio"       : "icmp_orphan_request_ratio",
    "fb_byte_asymmetry"         : "flow_byte_asymmetry",
    "fb_ttl_mean"               : "ip_ttl_mean",
    "fb_pkt_size_mean"          : "pkt_size_mean",
    "fb_pkt_size_std"           : "pkt_size_std",
    "fb_pkt_size_max"           : "pkt_size_max",
    "fb_pkt_size_median"        : "pkt_size_median",
    "fb_pkt_size_entropy"       : "pkt_size_entropy",
    "fb_pkt_size_skew"          : "pkt_size_skewness",
    "fb_pkt_size_kurt"          : "pkt_size_kurtosis",
    "fb_pkt_size_cv"            : "pkt_size_coeff_variation",
    "fb_pkt_size_iqr"           : "pkt_size_iqr",
    "fb_size_bin_0"             : "pkt_size_bin_60_240",
    "fb_size_bin_1"             : "pkt_size_bin_240_420",
    "fb_size_bin_2"             : "pkt_size_bin_420_600",
    "fb_size_bin_3"             : "pkt_size_bin_600_780",
    "fb_size_bin_4"             : "pkt_size_bin_780_960",
    "fb_size_bin_5"             : "pkt_size_bin_960_1140",
    "fb_size_bin_6"             : "pkt_size_bin_1140_1320",
    "fb_size_bin_7"             : "pkt_size_bin_1320_1442",
    "fb_size_trans_00"          : "pkt_size_trans_small_small",
    "fb_size_trans_01"          : "pkt_size_trans_small_med",
    "fb_size_trans_02"          : "pkt_size_trans_small_large",
    "fb_size_trans_03"          : "pkt_size_trans_small_xlarge",
    "fb_size_trans_10"          : "pkt_size_trans_med_small",
    "fb_size_trans_11"          : "pkt_size_trans_med_med",
    "fb_size_trans_12"          : "pkt_size_trans_med_large",
    "fb_size_trans_13"          : "pkt_size_trans_med_xlarge",
    "fb_size_trans_20"          : "pkt_size_trans_large_small",
    "fb_size_trans_21"          : "pkt_size_trans_large_med",
    "fb_size_trans_22"          : "pkt_size_trans_large_large",
    "fb_size_trans_23"          : "pkt_size_trans_large_xlarge",
    "fb_size_trans_30"          : "pkt_size_trans_xlarge_small",
    "fb_size_trans_31"          : "pkt_size_trans_xlarge_med",
    "fb_size_trans_32"          : "pkt_size_trans_xlarge_large",
    "fb_size_trans_33"          : "pkt_size_trans_xlarge_xlarge",
    "fb_uniform_size_ratio"     : "pkt_uniform_size_ratio",
    "fb_kl_div_baseline"        : "flow_kl_divergence_baseline",

    # ── TIME OBFUSCATION FEATURES ────────────────────────────────────────────
    "to_ipt_mean"               : "ipt_mean",
    "to_ipt_std"                : "ipt_std",
    "to_ipt_min"                : "ipt_min",
    "to_ipt_max"                : "ipt_max",
    "to_ipt_median"             : "ipt_median",
    "to_ipt_q90"                : "ipt_percentile_90",
    "to_ipt_q99"                : "ipt_percentile_99",
    "to_ipt_entropy"            : "ipt_entropy",
    "to_ipt_skew"               : "ipt_skewness",
    "to_ipt_cv"                 : "ipt_coeff_variation",
    "to_ipt_iqr"                : "ipt_iqr",
    "to_ipt_ac_1"               : "ipt_autocorr_lag1",
    "to_ipt_ac_2"               : "ipt_autocorr_lag2",
    "to_ipt_ac_3"               : "ipt_autocorr_lag3",
    "to_periodic_score"         : "ipt_periodicity_score",
    "to_timing_regularity"      : "ipt_timing_regularity",
    "to_jitter_mean"            : "ipt_jitter_mean",
    "to_jitter_std"             : "ipt_jitter_std",
}

# ── LOAD ──────────────────────────────────────────────────────────────────────
print("="*60)
print("ICMP — FEATURE RENAMING + RELABELING")
print("="*60)

df = pd.read_csv(INPUT_FILE)
print(f"\n[1] Loaded: {df.shape}")

# Verify all features in rename map exist
feat_cols = [c for c in df.columns if c not in ('label','label_name')]
missing   = [c for c in feat_cols if c not in RENAME_MAP]
unmapped  = [c for c in RENAME_MAP if c not in df.columns]
if missing:  print(f"  ⚠ Features not in rename map: {missing}")
if unmapped: print(f"  ⚠ Rename map keys not in CSV: {unmapped}")

# ── RENAME FEATURES ───────────────────────────────────────────────────────────
print("\n[2] Renaming 97 features ...")
df = df.rename(columns=RENAME_MAP)

# ── RELABEL ───────────────────────────────────────────────────────────────────
print("\n[3] Adding new label columns ...")
old_label = df['label'].copy()
df = df.drop(columns=['label', 'label_name'])

df['label_technique'] = old_label.map(TECHNIQUE_MAP).astype(int)
df['label_binary']    = 1
df['label_protocol']  = 'ICMP'

print(f"  label_technique:")
for v in sorted(df['label_technique'].unique()):
    print(f"    {v} = {TECHNIQUE_NAME[v]}: {(df['label_technique']==v).sum()}")
print(f"  label_binary   : 1 (all covert)")
print(f"  label_protocol : ICMP")

# ── SAVE ──────────────────────────────────────────────────────────────────────
label_cols = ['label_technique', 'label_binary', 'label_protocol']
new_feat_cols = [c for c in df.columns if c not in label_cols]
df = df[new_feat_cols + label_cols]

df.to_csv(OUTPUT_FILE, index=False)

print(f"\n[4] Saved → {OUTPUT_FILE}")
print(f"    Shape : {df.shape}  (1500 rows × 97 features + 3 labels)")
print(f"\n    Feature name samples:")
for col in list(df.columns[:5]) + list(df.columns[28:33]) + list(df.columns[69:74]):
    print(f"      {col}")

print(f"\n{'='*60}")
print(f"✅ DONE — icmp_model_ready.csv")
print(f"   Rows     : {len(df)}")
print(f"   Features : {len(new_feat_cols)}")
print(f"   Labels   : label_technique | label_binary | label_protocol")
print(f"{'='*60}")

============================================================
ICMP — FEATURE RENAMING + RELABELING
============================================================

[1] Loaded: (1500, 99)

[2] Renaming 97 features ...

[3] Adding new label columns ...
  label_technique:
    1 = Header_Manipulation: 500
    2 = Time_Obfuscation: 500
    3 = Flow_Blending: 500
  label_binary   : 1 (all covert)
  label_protocol : ICMP

[4] Saved → /content/icmp_model_ready.csv
    Shape : (1500, 100)  (1500 rows × 97 features + 3 labels)

    Feature name samples:
      icmp_type_code_entropy
      icmp_invalid_type_ratio
      icmp_non_echo_ratio
      icmp_type_diversity
      icmp_nonstandard_type_count
      payload_byte_entropy_mean
      payload_byte_entropy_std
      payload_compress_ratio_mean
      payload_compress_ratio_std
      payload_printable_ratio_mean
      pkt_size_trans_large_small
      pkt_size_trans_large_med
      pkt_size_trans_large_large
      pkt_size_trans_large_xlarge
      pkt_size_trans_xlarge_small

============================================================
✅ DONE — icmp_model_ready.csv
   Rows     : 1500
   Features : 97
   Labels   : label_technique | label_binary | label_protocol
============================================================

In [ ]:
model = pd.read_csv("/content/icmp_model_ready.csv")

In [ ]:
model.columns.to_list()

['icmp_type_code_entropy',
 'icmp_invalid_type_ratio',
 'icmp_non_echo_ratio',
 'icmp_type_diversity',
 'icmp_nonstandard_type_count',
 'icmp_code_field_entropy',
 'icmp_nonzero_code_ratio',
 'icmp_bad_checksum_ratio',
 'icmp_good_checksum_ratio',
 'icmp_checksum_entropy',
 'icmp_checksum_delta_mean',
 'icmp_checksum_delta_std',
 'ip_id_reuse_rate',
 'icmp_seq_increment_std',
 'icmp_seq_entropy',
 'icmp_seq_monotone_ratio',
 'icmp_seq_autocorr_lag1',
 'icmp_id_reuse_rate',
 'icmp_id_entropy',
 'icmp_id_delta_mean',
 'icmp_id_delta_std',
 'icmp_id_seq_correlation',
 'icmp_covert_id_count',
 'icmp_payload_len_mean',
 'icmp_payload_len_std',
 'icmp_payload_len_entropy',
 'icmp_payload_len_variance',
 'icmp_nonstd_payload_ratio',
 'payload_byte_entropy_mean',
 'payload_byte_entropy_std',
 'payload_compress_ratio_mean',
 'payload_compress_ratio_std',
 'payload_printable_ratio_mean',
 'payload_printable_ratio_std',
 'payload_null_byte_ratio_mean',
 'payload_null_byte_ratio_std',
 'payload_bigram_entropy_mean',
 'payload_bigram_entropy_std',
 'flow_total_bytes',
 'flow_duration_sec',
 'flow_bytes_per_sec',
 'icmp_orphan_request_ratio',
 'flow_byte_asymmetry',
 'ip_ttl_mean',
 'pkt_size_mean',
 'pkt_size_std',
 'pkt_size_max',
 'pkt_size_median',
 'pkt_size_entropy',
 'pkt_size_skewness',
 'pkt_size_kurtosis',
 'pkt_size_coeff_variation',
 'pkt_size_iqr',
 'pkt_size_bin_60_240',
 'pkt_size_bin_240_420',
 'pkt_size_bin_420_600',
 'pkt_size_bin_600_780',
 'pkt_size_bin_780_960',
 'pkt_size_bin_960_1140',
 'pkt_size_bin_1140_1320',
 'pkt_size_bin_1320_1442',
 'pkt_size_trans_small_small',
 'pkt_size_trans_small_med',
 'pkt_size_trans_small_large',
 'pkt_size_trans_small_xlarge',
 'pkt_size_trans_med_small',
 'pkt_size_trans_med_med',
 'pkt_size_trans_med_large',
 'pkt_size_trans_med_xlarge',
 'pkt_size_trans_large_small',
 'pkt_size_trans_large_med',
 'pkt_size_trans_large_large',
 'pkt_size_trans_large_xlarge',
 'pkt_size_trans_xlarge_small',
 'pkt_size_trans_xlarge_med',
 'pkt_size_trans_xlarge_large',
 'pkt_size_trans_xlarge_xlarge',
 'pkt_uniform_size_ratio',
 'flow_kl_divergence_baseline',
 'ipt_mean',
 'ipt_std',
 'ipt_min',
 'ipt_max',
 'ipt_median',
 'ipt_percentile_90',
 'ipt_percentile_99',
 'ipt_entropy',
 'ipt_skewness',
 'ipt_coeff_variation',
 'ipt_iqr',
 'ipt_autocorr_lag1',
 'ipt_autocorr_lag2',
 'ipt_autocorr_lag3',
 'ipt_periodicity_score',
 'ipt_timing_regularity',
 'ipt_jitter_mean',
 'ipt_jitter_std',
 'label_technique',
 'label_binary',
 'label_protocol']

# **Visualizations on Both normal and covert**

In [ ]:
# ============================================================
#   ICMP Covert Channel Detection — Dataset Visualizations
#   FYP | Run this notebook cell-by-cell in Google Colab
# ============================================================

# ─────────────────────────────────────────────
# CELL 1 — Install & Imports
# ─────────────────────────────────────────────
!pip install -q scikit-learn seaborn matplotlib pandas numpy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.ensemble import RandomForestClassifier
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Global style
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams.update({'figure.dpi': 130, 'font.size': 11})

COVERT_COLOR  = '#E74C3C'
NORMAL_COLOR  = '#2ECC71'
PALETTE       = {0: NORMAL_COLOR, 1: COVERT_COLOR}
LABEL_MAP     = {0: 'Normal', 1: 'Covert'}
TECH_MAP      = {0: 'Normal', 1: 'Technique-1', 2: 'Technique-2', 3: 'Technique-3'}

print("✅ Libraries loaded successfully.")


# ─────────────────────────────────────────────
# CELL 2 — Load & Merge Datasets
# ─────────────────────────────────────────────
# Upload both CSV files to Colab, then run:
from google.colab import files
print("Upload icmp_model_ready_covert.csv  and  icmp_normal_labeled.csv")
uploaded = files.upload()

covert_df = pd.read_csv('/content/drive/MyDrive/3_levels_Protocol_Wise/ICMP/icmp_covert_labeled.csv')
normal_df  = pd.read_csv('/content/drive/MyDrive/3_levels_Protocol_Wise/ICMP/icmp_normal_labeled.csv')

# Align columns — keep only common features + labels
label_cols   = ['label_binary', 'label_technique', 'label_protocol']
common_feats = sorted(set(normal_df.columns) & set(covert_df.columns) - set(label_cols))

# Rename normal-only field names to match covert naming
rename_map = {'id_entropy': 'icmp_id_entropy',
              'seq_entropy': 'icmp_seq_entropy',
              'payload_len_mean': 'icmp_payload_len_mean',
              'payload_len_std':  'icmp_payload_len_std',
              'payload_len_entropy': 'icmp_payload_len_entropy'}
normal_df.rename(columns=rename_map, inplace=True)

# Combined dataset (using common features only for cross-dataset analysis)
combined_feats = sorted(set(normal_df.columns) & set(covert_df.columns) - set(label_cols))
combined_df = pd.concat([
    normal_df[combined_feats + label_cols],
    covert_df[combined_feats + label_cols]
], ignore_index=True)

# Full covert-only dataset (all 97 features)
covert_feats = [c for c in covert_df.columns if c not in label_cols]

print(f"✅ Normal  : {len(normal_df):,} rows | {len(normal_df.columns)-3} features")
print(f"✅ Covert  : {len(covert_df):,} rows | {len(covert_feats)} features")
print(f"✅ Combined: {len(combined_df):,} rows | {len(combined_feats)} shared features")
print(f"   Class distribution:\n{combined_df['label_binary'].map(LABEL_MAP).value_counts()}")


# ─────────────────────────────────────────────
# CELL 3 — Dataset Overview: Class Distribution
# ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle("ICMP Dataset Overview", fontsize=15, fontweight='bold', y=1.02)

# ── 3A: Binary class pie ──
counts = combined_df['label_binary'].map(LABEL_MAP).value_counts()
axes[0].pie(counts, labels=counts.index, autopct='%1.1f%%',
            colors=[NORMAL_COLOR, COVERT_COLOR], startangle=90,
            wedgeprops={'edgecolor':'white','linewidth':2})
axes[0].set_title("Binary Class Distribution\n(Normal vs Covert)")

# ── 3B: Technique breakdown bar ──
tech_counts = combined_df['label_technique'].map(TECH_MAP).value_counts().sort_index()
colors_tech = [NORMAL_COLOR, '#3498DB', '#9B59B6', COVERT_COLOR]
bars = axes[1].bar(tech_counts.index, tech_counts.values, color=colors_tech, edgecolor='white', linewidth=1.2)
axes[1].set_title("Samples per Class/Technique")
axes[1].set_ylabel("Number of Flows")
axes[1].set_xlabel("Class / Technique")
for bar, val in zip(bars, tech_counts.values):
    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+20,
                 str(val), ha='center', fontweight='bold')

# ── 3C: Feature group counts (covert dataset) ──
feature_groups = {
    'Type & Code': 7, 'Checksum': 5, 'Seq & ID': 11,
    'Payload Length': 5, 'Payload Content': 10,
    'Flow & IP': 6, 'Packet Size': 35, 'Timing (IPT)': 18
}
gnames = list(feature_groups.keys())
gcounts = list(feature_groups.values())
colors_fg = plt.cm.Set2(np.linspace(0, 1, len(gnames)))
hbars = axes[2].barh(gnames, gcounts, color=colors_fg, edgecolor='white')
axes[2].set_title("Features per Group\n(Covert Dataset — 97 total)")
axes[2].set_xlabel("Number of Features")
for bar, val in zip(hbars, gcounts):
    axes[2].text(bar.get_width()+0.2, bar.get_y()+bar.get_height()/2,
                 str(val), va='center', fontweight='bold')

plt.tight_layout()
plt.savefig('fig1_dataset_overview.png', bbox_inches='tight')
plt.show()
print("✅ Figure 1 saved.")


# ─────────────────────────────────────────────
# CELL 4 — Flow-Level Feature Distributions (Normal vs Covert)
# ─────────────────────────────────────────────
flow_features = ['flow_total_bytes', 'flow_bytes_per_sec', 'flow_duration_sec',
                 'ip_ttl_mean', 'pkt_size_mean', 'pkt_size_std',
                 'pkt_size_entropy', 'pkt_size_coeff_variation']

fig, axes = plt.subplots(2, 4, figsize=(20, 9))
fig.suptitle("Flow-Level Feature Distributions: Normal vs Covert", fontsize=14, fontweight='bold')
axes = axes.flatten()

for i, feat in enumerate(flow_features):
    if feat not in combined_df.columns:
        axes[i].set_visible(False)
        continue
    for label_val, color, lname in [(0, NORMAL_COLOR, 'Normal'), (1, COVERT_COLOR, 'Covert')]:
        data = combined_df[combined_df['label_binary']==label_val][feat].dropna()
        data_clipped = np.clip(data, data.quantile(0.01), data.quantile(0.99))
        axes[i].hist(data_clipped, bins=40, alpha=0.6, color=color,
                     label=lname, density=True, edgecolor='none')
    axes[i].set_title(feat.replace('_', ' ').title(), fontsize=10)
    axes[i].set_ylabel("Density")
    if i == 0:
        axes[i].legend(fontsize=9)

plt.tight_layout()
plt.savefig('fig2_flow_distributions.png', bbox_inches='tight')
plt.show()
print("✅ Figure 2 saved.")


# ─────────────────────────────────────────────
# CELL 5 — Timing (IPT) Feature Distributions
# ─────────────────────────────────────────────
ipt_features = ['ipt_mean', 'ipt_std', 'ipt_entropy', 'ipt_skewness',
                'ipt_coeff_variation', 'ipt_autocorr_lag1',
                'ipt_percentile_90', 'ipt_iqr']

fig, axes = plt.subplots(2, 4, figsize=(20, 9))
fig.suptitle("Inter-Packet Timing (IPT) Features: Normal vs Covert", fontsize=14, fontweight='bold')
axes = axes.flatten()

for i, feat in enumerate(ipt_features):
    for label_val, color, lname in [(0, NORMAL_COLOR, 'Normal'), (1, COVERT_COLOR, 'Covert')]:
        data = combined_df[combined_df['label_binary']==label_val][feat].dropna()
        data_clipped = np.clip(data, data.quantile(0.01), data.quantile(0.99))
        axes[i].hist(data_clipped, bins=40, alpha=0.6, color=color,
                     label=lname, density=True, edgecolor='none')
    axes[i].set_title(feat.replace('_', ' ').title(), fontsize=10)
    axes[i].set_ylabel("Density")
    if i == 0:
        axes[i].legend(fontsize=9)

plt.tight_layout()
plt.savefig('fig3_ipt_distributions.png', bbox_inches='tight')
plt.show()
print("✅ Figure 3 saved.")


# ─────────────────────────────────────────────
# CELL 6 — ICMP-Specific Features (Covert Only): Boxplots by Technique
# ─────────────────────────────────────────────
icmp_feats = ['icmp_type_code_entropy', 'icmp_invalid_type_ratio',
              'icmp_type_diversity', 'icmp_nonstandard_type_count',
              'icmp_bad_checksum_ratio', 'icmp_checksum_entropy',
              'icmp_covert_id_count', 'icmp_seq_entropy',
              'icmp_id_entropy', 'icmp_payload_len_mean',
              'icmp_nonstd_payload_ratio', 'icmp_orphan_request_ratio']

fig, axes = plt.subplots(3, 4, figsize=(20, 13))
fig.suptitle("ICMP-Specific Features by Covert Technique", fontsize=14, fontweight='bold')
axes = axes.flatten()
tech_palette = {'Technique-1': '#3498DB', 'Technique-2': '#9B59B6', 'Technique-3': COVERT_COLOR}

covert_df['Technique'] = covert_df['label_technique'].map({1:'Technique-1',2:'Technique-2',3:'Technique-3'})

for i, feat in enumerate(icmp_feats):
    if feat in covert_df.columns:
        sns.boxplot(data=covert_df, x='Technique', y=feat,
                    palette=tech_palette, ax=axes[i], width=0.5,
                    flierprops=dict(marker='o', markersize=2, alpha=0.4))
        axes[i].set_title(feat.replace('_', ' ').replace('icmp ', '').title(), fontsize=9)
        axes[i].set_xlabel("")
        axes[i].set_ylabel("")
        axes[i].tick_params(axis='x', labelsize=8)

plt.tight_layout()
plt.savefig('fig4_icmp_features_by_technique.png', bbox_inches='tight')
plt.show()
print("✅ Figure 4 saved.")


# ─────────────────────────────────────────────
# CELL 7 — Payload Content Features: Normal vs Covert
# ─────────────────────────────────────────────
# Map normal payload features for comparison
payload_map = {
    'icmp_payload_len_mean':    ('icmp_payload_len_mean',  'payload_len_mean'),
    'icmp_payload_len_entropy': ('icmp_payload_len_entropy','payload_len_entropy'),
    'icmp_payload_len_std':     ('icmp_payload_len_std',   'payload_len_std'),
}
payload_covert_only = ['payload_byte_entropy_mean', 'payload_compress_ratio_mean',
                       'payload_printable_ratio_mean', 'payload_null_byte_ratio_mean',
                       'payload_bigram_entropy_mean']

fig, axes = plt.subplots(2, 4, figsize=(20, 9))
fig.suptitle("Payload Feature Analysis: Normal vs Covert", fontsize=14, fontweight='bold')
axes = axes.flatten()

plot_idx = 0
# Comparable features
for title, (c_feat, n_feat) in payload_map.items():
    ax = axes[plot_idx]
    n_feat_actual = n_feat if n_feat in normal_df.columns else c_feat
    for data, color, lname in [
        (normal_df[n_feat_actual].dropna() if n_feat_actual in normal_df.columns
         else normal_df.get(c_feat, pd.Series()).dropna(), NORMAL_COLOR, 'Normal'),
        (covert_df[c_feat].dropna(), COVERT_COLOR, 'Covert')
    ]:
        clipped = np.clip(data, data.quantile(0.01), data.quantile(0.99))
        ax.hist(clipped, bins=40, alpha=0.6, color=color, label=lname, density=True)
    ax.set_title(title.replace('icmp_','').replace('_',' ').title(), fontsize=10)
    ax.set_ylabel("Density")
    if plot_idx == 0:
        ax.legend(fontsize=9)
    plot_idx += 1

# Covert-only payload features
for feat in payload_covert_only:
    if plot_idx >= 8:
        break
    ax = axes[plot_idx]
    sns.boxplot(data=covert_df, x='Technique', y=feat,
                palette=tech_palette, ax=ax, width=0.5)
    ax.set_title(feat.replace('_mean','').replace('_',' ').title(), fontsize=9)
    ax.set_xlabel(""); ax.set_ylabel("")
    ax.tick_params(axis='x', labelsize=8)
    plot_idx += 1

plt.tight_layout()
plt.savefig('fig5_payload_features.png', bbox_inches='tight')
plt.show()
print("✅ Figure 5 saved.")


# ─────────────────────────────────────────────
# CELL 8 — Correlation Heatmap (Covert Dataset)
# ─────────────────────────────────────────────
key_feats = [
    'icmp_type_code_entropy', 'icmp_type_diversity', 'icmp_nonstandard_type_count',
    'icmp_bad_checksum_ratio', 'icmp_checksum_entropy',
    'icmp_covert_id_count', 'icmp_seq_entropy', 'icmp_id_entropy',
    'icmp_payload_len_mean', 'icmp_nonstd_payload_ratio',
    'payload_byte_entropy_mean', 'payload_printable_ratio_mean',
    'flow_total_bytes', 'flow_bytes_per_sec',
    'pkt_size_mean', 'pkt_size_entropy',
    'ipt_mean', 'ipt_entropy', 'ipt_timing_regularity',
    'icmp_orphan_request_ratio', 'flow_byte_asymmetry'
]
key_feats = [f for f in key_feats if f in covert_df.columns]

corr_matrix = covert_df[key_feats].corr()
short_labels = [f.replace('icmp_','').replace('payload_','').replace('flow_','')
                 .replace('pkt_','').replace('ipt_','').replace('_mean','_μ')
                 .replace('_entropy','_ent').replace('_ratio','_r') for f in key_feats]

fig, ax = plt.subplots(figsize=(16, 13))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r',
            center=0, vmin=-1, vmax=1, ax=ax, linewidths=0.3,
            xticklabels=short_labels, yticklabels=short_labels,
            annot_kws={'size': 7}, cbar_kws={'shrink': 0.8})
ax.set_title("Feature Correlation Matrix — ICMP Covert Dataset\n(Key Features)", fontsize=13, fontweight='bold')
ax.tick_params(axis='x', rotation=45, labelsize=8)
ax.tick_params(axis='y', rotation=0,  labelsize=8)

plt.tight_layout()
plt.savefig('fig6_correlation_heatmap.png', bbox_inches='tight')
plt.show()
print("✅ Figure 6 saved.")


# ─────────────────────────────────────────────
# CELL 9 — PCA: 2D Projection (Normal vs Covert)
# ─────────────────────────────────────────────
shared = [f for f in combined_feats if f not in label_cols]
X = combined_df[shared].fillna(combined_df[shared].median())
y = combined_df['label_binary'].values
y_tech = combined_df['label_technique'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle("PCA — 2D Projection of ICMP Flows", fontsize=14, fontweight='bold')

# Binary
for label_val, color, lname in [(0, NORMAL_COLOR, 'Normal'), (1, COVERT_COLOR, 'Covert')]:
    mask = y == label_val
    axes[0].scatter(X_pca[mask, 0], X_pca[mask, 1], c=color, alpha=0.4,
                    s=10, label=lname, rasterized=True)
axes[0].set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% variance)")
axes[0].set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% variance)")
axes[0].set_title("Normal vs Covert")
axes[0].legend(markerscale=2)

# By technique
tech_colors = {0: NORMAL_COLOR, 1: '#3498DB', 2: '#9B59B6', 3: COVERT_COLOR}
for t, color in tech_colors.items():
    mask = y_tech == t
    axes[1].scatter(X_pca[mask, 0], X_pca[mask, 1], c=color, alpha=0.4,
                    s=10, label=TECH_MAP[t], rasterized=True)
axes[1].set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% variance)")
axes[1].set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% variance)")
axes[1].set_title("By Covert Technique")
axes[1].legend(markerscale=2)

plt.tight_layout()
plt.savefig('fig7_pca_projection.png', bbox_inches='tight')
plt.show()
print(f"✅ Figure 7 saved. | PC1+PC2 explains {sum(pca.explained_variance_ratio_[:2])*100:.1f}% variance")


# ─────────────────────────────────────────────
# CELL 10 — t-SNE: Cluster Visualization
# ─────────────────────────────────────────────
# Subsample for speed
np.random.seed(42)
idx = np.random.choice(len(X_scaled), size=min(2000, len(X_scaled)), replace=False)
X_tsne_input = X_scaled[idx]
y_tsne = y[idx]
y_tech_tsne = y_tech[idx]

print("Running t-SNE (may take ~1-2 minutes)...")
tsne = TSNE(n_components=2, random_state=42, perplexity=40, n_iter=1000)
X_tsne = tsne.fit_transform(X_tsne_input)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle("t-SNE — 2D Cluster Visualization of ICMP Flows", fontsize=14, fontweight='bold')

for label_val, color, lname in [(0, NORMAL_COLOR, 'Normal'), (1, COVERT_COLOR, 'Covert')]:
    mask = y_tsne == label_val
    axes[0].scatter(X_tsne[mask, 0], X_tsne[mask, 1], c=color, alpha=0.5,
                    s=10, label=lname, rasterized=True)
axes[0].set_title("Normal vs Covert")
axes[0].set_xlabel("t-SNE Dim 1"); axes[0].set_ylabel("t-SNE Dim 2")
axes[0].legend(markerscale=2)

for t, color in tech_colors.items():
    mask = y_tech_tsne == t
    axes[1].scatter(X_tsne[mask, 0], X_tsne[mask, 1], c=color, alpha=0.5,
                    s=10, label=TECH_MAP[t], rasterized=True)
axes[1].set_title("By Covert Technique")
axes[1].set_xlabel("t-SNE Dim 1"); axes[1].set_ylabel("t-SNE Dim 2")
axes[1].legend(markerscale=2)

plt.tight_layout()
plt.savefig('fig8_tsne_visualization.png', bbox_inches='tight')
plt.show()
print("✅ Figure 8 saved.")


# ─────────────────────────────────────────────
# CELL 11 — Feature Importance (Random Forest)
# ─────────────────────────────────────────────
# On full covert dataset (all 97 features) — binary classification
X_full = covert_df[covert_feats].fillna(covert_df[covert_feats].median())
y_full = covert_df['label_technique'].values  # multi-class technique detection

rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X_full, y_full)

importances = pd.Series(rf.feature_importances_, index=covert_feats).sort_values(ascending=False)
top20 = importances.head(20)

fig, ax = plt.subplots(figsize=(12, 8))
colors_imp = plt.cm.RdYlGn_r(np.linspace(0.1, 0.8, len(top20)))
bars = ax.barh(range(len(top20)), top20.values[::-1], color=colors_imp[::-1], edgecolor='white')
ax.set_yticks(range(len(top20)))
ax.set_yticklabels([f.replace('_', ' ') for f in top20.index[::-1]], fontsize=9)
ax.set_xlabel("Feature Importance Score", fontsize=11)
ax.set_title("Top 20 Most Important Features\n(Random Forest — Technique Classification)", fontsize=13, fontweight='bold')
for bar, val in zip(bars, top20.values[::-1]):
    ax.text(bar.get_width()+0.001, bar.get_y()+bar.get_height()/2,
            f'{val:.4f}', va='center', fontsize=8)

plt.tight_layout()
plt.savefig('fig9_feature_importance.png', bbox_inches='tight')
plt.show()
print("✅ Figure 9 saved.")
print("Top 5 most important features:")
for feat, imp in top20.head(5).items():
    print(f"  {feat}: {imp:.4f}")


# ─────────────────────────────────────────────
# CELL 12 — Violin Plots: Top Discriminating Features
# ─────────────────────────────────────────────
top_disc_feats = list(top20.index[:8])
covert_df['Class'] = 'Covert'
normal_df['Class']  = 'Normal'

fig, axes = plt.subplots(2, 4, figsize=(20, 10))
fig.suptitle("Top Discriminating Features — Violin Plots by Technique", fontsize=14, fontweight='bold')
axes = axes.flatten()

for i, feat in enumerate(top_disc_feats):
    if feat in covert_df.columns:
        sns.violinplot(data=covert_df, x='Technique', y=feat,
                       palette=tech_palette, ax=axes[i], cut=0, inner='box')
        axes[i].set_title(feat.replace('_', ' ').replace('icmp ', '').title(), fontsize=9)
        axes[i].set_xlabel(""); axes[i].set_ylabel("")
        axes[i].tick_params(axis='x', labelsize=8)

plt.tight_layout()
plt.savefig('fig10_violin_top_features.png', bbox_inches='tight')
plt.show()
print("✅ Figure 10 saved.")


# ─────────────────────────────────────────────
# CELL 13 — Statistical Significance (Mann-Whitney U Test)
# ─────────────────────────────────────────────
shared_analysis = [f for f in combined_feats if f not in label_cols]
normal_data  = combined_df[combined_df['label_binary']==0]
covert_data  = combined_df[combined_df['label_binary']==1]

results = []
for feat in shared_analysis:
    n_vals = normal_data[feat].dropna()
    c_vals = covert_data[feat].dropna()
    stat, pval = stats.mannwhitneyu(n_vals, c_vals, alternative='two-sided')
    effect = abs(n_vals.mean() - c_vals.mean()) / (np.sqrt((n_vals.std()**2 + c_vals.std()**2)/2) + 1e-9)
    results.append({'feature': feat, 'p_value': pval, 'effect_size': effect,
                    'normal_mean': n_vals.mean(), 'covert_mean': c_vals.mean()})

stat_df = pd.DataFrame(results).sort_values('effect_size', ascending=False)
sig_df  = stat_df[stat_df['p_value'] < 0.05].head(15)

fig, axes = plt.subplots(1, 2, figsize=(18, 7))
fig.suptitle("Statistical Significance: Normal vs Covert (Shared Features)", fontsize=13, fontweight='bold')

# Effect size bar chart
colors_eff = ['#E74C3C' if e > 1.0 else '#F39C12' if e > 0.5 else '#2ECC71'
              for e in sig_df['effect_size']]
bars = axes[0].barh(range(len(sig_df)), sig_df['effect_size'],
                    color=colors_eff, edgecolor='white')
axes[0].set_yticks(range(len(sig_df)))
axes[0].set_yticklabels([f.replace('_',' ') for f in sig_df['feature']], fontsize=9)
axes[0].set_xlabel("Cohen's d Effect Size")
axes[0].set_title("Top Features by Effect Size")
axes[0].axvline(x=0.5, color='orange', linestyle='--', alpha=0.7, label='Medium effect')
axes[0].axvline(x=1.0, color='red',    linestyle='--', alpha=0.7, label='Large effect')
axes[0].legend(fontsize=8)

# Mean comparison scatter
axes[1].scatter(sig_df['normal_mean'], sig_df['covert_mean'],
                c=sig_df['effect_size'], cmap='RdYlGn_r', s=100,
                edgecolors='gray', linewidths=0.5, zorder=3)
lim_min = min(sig_df['normal_mean'].min(), sig_df['covert_mean'].min())
lim_max = max(sig_df['normal_mean'].max(), sig_df['covert_mean'].max())
axes[1].plot([lim_min, lim_max], [lim_min, lim_max], 'k--', alpha=0.4, label='y=x (no diff)')
axes[1].set_xlabel("Normal Mean"); axes[1].set_ylabel("Covert Mean")
axes[1].set_title("Feature Means: Normal vs Covert\n(Points above diagonal = higher in covert)")
for _, row in sig_df.head(6).iterrows():
    axes[1].annotate(row['feature'].replace('_',' ')[:20],
                     (row['normal_mean'], row['covert_mean']),
                     fontsize=7, alpha=0.8)
axes[1].legend(fontsize=8)

plt.tight_layout()
plt.savefig('fig11_statistical_significance.png', bbox_inches='tight')
plt.show()
print("✅ Figure 11 saved.")
print("\nTop 10 most discriminating features:")
print(sig_df[['feature','p_value','effect_size','normal_mean','covert_mean']].head(10).to_string(index=False))


# ─────────────────────────────────────────────
# CELL 14 — Packet Size Distribution Analysis
# ─────────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle("Packet Size Analysis: Normal vs Covert", fontsize=14, fontweight='bold')
axes = axes.flatten()

# Size histogram overlay
for label_val, color, lname in [(0, NORMAL_COLOR, 'Normal'), (1, COVERT_COLOR, 'Covert')]:
    data = combined_df[combined_df['label_binary']==label_val]['pkt_size_mean'].dropna()
    axes[0].hist(data, bins=50, alpha=0.6, color=color, label=lname, density=True)
axes[0].set_title("Packet Size Mean Distribution"); axes[0].legend()
axes[0].set_xlabel("Mean Packet Size (bytes)"); axes[0].set_ylabel("Density")

# Size entropy
for label_val, color, lname in [(0, NORMAL_COLOR, 'Normal'), (1, COVERT_COLOR, 'Covert')]:
    data = combined_df[combined_df['label_binary']==label_val]['pkt_size_entropy'].dropna()
    axes[1].hist(data, bins=40, alpha=0.6, color=color, label=lname, density=True)
axes[1].set_title("Packet Size Entropy"); axes[1].legend()
axes[1].set_xlabel("Entropy"); axes[1].set_ylabel("Density")

# Coeff of variation boxplot
sns.boxplot(data=combined_df, x=combined_df['label_binary'].map(LABEL_MAP),
            y='pkt_size_coeff_variation', palette={'Normal': NORMAL_COLOR, 'Covert': COVERT_COLOR},
            ax=axes[2])
axes[2].set_title("Packet Size Coefficient of Variation")
axes[2].set_xlabel("Class"); axes[2].set_ylabel("Coeff of Variation")

# Size bins (covert only)
bin_feats = [c for c in covert_df.columns if c.startswith('pkt_size_bin_')]
bin_means = covert_df.groupby('Technique')[bin_feats].mean()
bin_labels = [b.replace('pkt_size_bin_','') for b in bin_feats]
x = np.arange(len(bin_feats))
width = 0.25
for j, (tech, color) in enumerate([('Technique-1','#3498DB'),('Technique-2','#9B59B6'),('Technique-3',COVERT_COLOR)]):
    axes[3].bar(x + j*width, bin_means.loc[tech], width, label=tech, color=color, alpha=0.8)
axes[3].set_xticks(x + width)
axes[3].set_xticklabels(bin_labels, rotation=35, fontsize=7)
axes[3].set_title("Packet Size Bin Distribution\n(by Covert Technique)")
axes[3].set_ylabel("Mean Proportion"); axes[3].legend(fontsize=8)

# Skewness comparison
sns.violinplot(data=combined_df, x=combined_df['label_binary'].map(LABEL_MAP),
               y='pkt_size_skewness', palette={'Normal': NORMAL_COLOR, 'Covert': COVERT_COLOR},
               ax=axes[4], cut=0)
axes[4].set_title("Packet Size Skewness"); axes[4].set_xlabel("Class")

# Uniform size ratio (covert only)
sns.boxplot(data=covert_df, x='Technique', y='pkt_uniform_size_ratio',
            palette=tech_palette, ax=axes[5])
axes[5].set_title("Uniform Packet Size Ratio\n(Covert Techniques)")
axes[5].set_xlabel(""); axes[5].set_ylabel("Ratio")

plt.tight_layout()
plt.savefig('fig12_packet_size_analysis.png', bbox_inches='tight')
plt.show()
print("✅ Figure 12 saved.")


# ─────────────────────────────────────────────
# CELL 15 — Summary Statistics Table
# ─────────────────────────────────────────────
key_compare = ['flow_total_bytes', 'flow_bytes_per_sec', 'pkt_size_mean',
               'pkt_size_entropy', 'ipt_mean', 'ipt_entropy',
               'ipt_coeff_variation', 'pkt_size_coeff_variation']
key_compare = [f for f in key_compare if f in combined_df.columns]

summary_rows = []
for feat in key_compare:
    n = combined_df[combined_df['label_binary']==0][feat].dropna()
    c = combined_df[combined_df['label_binary']==1][feat].dropna()
    _, pval = stats.mannwhitneyu(n, c, alternative='two-sided')
    summary_rows.append({
        'Feature': feat.replace('_',' ').title(),
        'Normal Mean': f"{n.mean():.4f}",
        'Normal Std':  f"{n.std():.4f}",
        'Covert Mean': f"{c.mean():.4f}",
        'Covert Std':  f"{c.std():.4f}",
        'p-value': f"{pval:.2e}",
        'Significant': '✅' if pval < 0.05 else '❌'
    })

summary_table = pd.DataFrame(summary_rows)

fig, ax = plt.subplots(figsize=(16, 5))
ax.axis('off')
tbl = ax.table(cellText=summary_table.values, colLabels=summary_table.columns,
               cellLoc='center', loc='center', bbox=[0, 0, 1, 1])
tbl.auto_set_font_size(False); tbl.set_fontsize(9)
tbl.auto_set_column_width(col=list(range(len(summary_table.columns))))
for j in range(len(summary_table.columns)):
    tbl[(0, j)].set_facecolor('#2C3E50')
    tbl[(0, j)].set_text_props(color='white', fontweight='bold')
for i in range(1, len(summary_table)+1):
    clr = '#FADBD8' if summary_table.iloc[i-1]['Significant']=='✅' else '#D5F5E3'
    for j in range(len(summary_table.columns)):
        tbl[(i, j)].set_facecolor(clr)

ax.set_title("Statistical Summary — Key Features: Normal vs Covert",
             fontsize=13, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('fig13_summary_table.png', bbox_inches='tight')
plt.show()
print("✅ Figure 13 saved.")


# ─────────────────────────────────────────────
# CELL 16 — Download All Figures
# ─────────────────────────────────────────────
import zipfile, os
figs = [f'fig{i}_{n}.png' for i, n in enumerate([
    'dataset_overview', 'flow_distributions', 'ipt_distributions',
    'icmp_features_by_technique', 'payload_features', 'correlation_heatmap',
    'pca_projection', 'tsne_visualization', 'feature_importance',
    'violin_top_features', 'statistical_significance',
    'packet_size_analysis', 'summary_table'], start=1)]

with zipfile.ZipFile('icmp_visualizations.zip', 'w') as zf:
    for f in figs:
        if os.path.exists(f):
            zf.write(f)

files.download('icmp_visualizations.zip')
print("✅ All figures zipped and downloaded!")
print("\n📊 VISUALIZATION SUMMARY:")
print("  Fig 1  — Dataset Overview (class distribution, feature groups)")
print("  Fig 2  — Flow-Level Feature Distributions (Normal vs Covert)")
print("  Fig 3  — IPT Timing Feature Distributions")
print("  Fig 4  — ICMP-Specific Features by Technique (boxplots)")
print("  Fig 5  — Payload Content Feature Analysis")
print("  Fig 6  — Feature Correlation Heatmap (key 21 features)")
print("  Fig 7  — PCA 2D Projection")
print("  Fig 8  — t-SNE Cluster Visualization")
print("  Fig 9  — Random Forest Feature Importance (Top 20)")
print("  Fig 10 — Violin Plots (Top Discriminating Features)")
print("  Fig 11 — Statistical Significance (Mann-Whitney U)")
print("  Fig 12 — Packet Size Distribution Analysis")
print("  Fig 13 — Summary Statistics Table")

Output hidden; open in https://colab.research.google.com to view.